/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ecumarket;

import Modelo.DetalleFactura;
import java.util.List;

/**
 *
 * @author Adrian
 */
public class Factura extends javax.swing.JPanel {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Fecha_de_venta = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel_Metodo_de_pago = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel_Total = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        jButton_buscar_Cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Producto = new javax.swing.JComboBox<>();
        txt_cliente_buscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Precio = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jLabel_Subtotal = new javax.swing.JLabel();
        jTextField_Subtotal = new javax.swing.JTextField();
        jLabel_Iva = new javax.swing.JLabel();
        jTextField_Iva = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btnElimiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Cliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Fecha_de_venta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Fecha_de_venta.setText("Fecha de venta:");
        jPanel1.add(jLabel_Fecha_de_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 185, -1));

        jLabel_Metodo_de_pago.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Metodo_de_pago.setText("Metodo de pago:");
        jPanel1.add(jLabel_Metodo_de_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 177, -1));

        jLabel_Total.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Total.setText("Total:");
        jPanel1.add(jLabel_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paypal", "Banco Pichincha", "Banco Guayaquil", "Produbanco" }));
        jPanel1.add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 143, -1));

        jButton_buscar_Cliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton_buscar_Cliente.setText("buscar");
        jButton_buscar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_buscar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 100, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("FACTURACION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 80, 20));

        jComboBox_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione producto", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 130, -1));

        txt_cliente_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cliente_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cliente_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 110, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 70, -1));
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        jPanel1.add(jTextField_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, -1));

        jButton_Guardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 140, 50));

        jLabel_Subtotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Subtotal.setText("Subtotal:");
        jPanel1.add(jLabel_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        jPanel1.add(jTextField_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 130, -1));

        jLabel_Iva.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Iva.setText("Iva:");
        jPanel1.add(jLabel_Iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        jPanel1.add(jTextField_Iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, 20));

        btnagregar.setText("Agregar Producto");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 140, 50));

        btnElimiar.setText("Eliminar Producto");
        btnElimiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnElimiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 140, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Cliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_Cliente.setText("Cliente:");
        jPanel2.add(jLabel_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel2.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        jLabel5.setText("Fecha");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos a Agregar"));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 210, 120));

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetallesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_buscar_ClienteActionPerformed

    private void txt_cliente_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cliente_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cliente_buscarActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
       
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

       
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnElimiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiarActionPerformed
       
    }//GEN-LAST:event_btnElimiarActionPerformed

    private void tablaDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetallesMouseClicked
       
    }//GEN-LAST:event_tablaDetallesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimiar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_buscar_Cliente;
    private javax.swing.JComboBox<String> jComboBox_Producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_Fecha_de_venta;
    private javax.swing.JLabel jLabel_Iva;
    private javax.swing.JLabel jLabel_Metodo_de_pago;
    private javax.swing.JLabel jLabel_Subtotal;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_Iva;
    private javax.swing.JTextField jTextField_Precio;
    private javax.swing.JTextField jTextField_Subtotal;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cliente_buscar;
    // End of variables declaration//GEN-END:variables
}
