package com.mycompany.ecumarket;

import Modelo.Categoria;
import Modelo.Crlt_Categoria;
import java.awt.Dimension;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author tadeo
 */
public class InterCategoria extends javax.swing.JInternalFrame {

    public InterCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_DescripcionCate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_DescripcionCate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion Categoria:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 12))); // NOI18N
        jPanel1.add(txt_DescripcionCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 28, 370, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         Categoria categoria = new Categoria();
    Crlt_Categoria controlCategoria = new Crlt_Categoria();

    String descripcion = txt_DescripcionCate.getText().trim();

    if (descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ Complete todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
    } else {
        if (!controlCategoria.existeCategoria(descripcion)) {
            categoria.setDescripcion(descripcion);
            categoria.setEstado(1); // Estado activo

            if (controlCategoria.guardar(categoria)) {
                JOptionPane.showMessageDialog(this, "✅ Categoría guardada exitosamente", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al guardar la categoría", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ La categoría ya está registrada en la base de datos", "Categoría existente", JOptionPane.WARNING_MESSAGE);
        }
    }

    txt_DescripcionCate.setText(""); // Limpiar el campo siempre al final
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DescripcionCate;
    // End of variables declaration//GEN-END:variables
}
