/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ecumarket;

import java.awt.Color;

/**
 *
 * @author LENOVO IDEAPAD
 */
public class loginpanel extends javax.swing.JPanel {

    /**
     * Creates new form loginpanel
     */
    public loginpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtcontrase = new javax.swing.JPasswordField();
        btnentrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(960, 410));
        setPreferredSize(new java.awt.Dimension(960, 410));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 339));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Inicia sesion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Correo electronico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtcorreo.setText("alguien@example.com");
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 310, -1));

        txtcontrase.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcontrase.setForeground(new java.awt.Color(204, 204, 204));
        txtcontrase.setText("********");
        txtcontrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcontraseMousePressed(evt);
            }
        });
        jPanel1.add(txtcontrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 310, -1));

        btnentrar.setBackground(new java.awt.Color(0, 153, 255));
        btnentrar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Entrar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 200, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/lalaa.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 240, 220));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ECUMARKET");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 370, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private PantallaPrincipal pantallaPrincipal;

public loginpanel(PantallaPrincipal pantallaPrincipal) {
    initComponents();
    this.pantallaPrincipal = pantallaPrincipal;
}

    private void txtcontraseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseMousePressed
if(String.valueOf(txtcontrase.getPassword()).equals("********")){
        txtcontrase.setText("");
txtcontrase.setForeground(Color.black);
}
if(txtcorreo.getText().isEmpty()){
txtcorreo.setText("alguien@example.com");
txtcorreo.setForeground(Color.gray);}
// TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseMousePressed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        if(String.valueOf(txtcontrase.getPassword()).isEmpty()){
        txtcontrase.setText("********");
txtcontrase.setForeground(Color.gray);
}
if(txtcorreo.getText().equals("alguien@example.com")){
txtcorreo.setText("");
txtcorreo.setForeground(Color.black);}
    }//GEN-LAST:event_txtcorreoMousePressed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
       Clases.UsuarioDao objetoLogin = new Clases.UsuarioDao();

    String correo = txtcorreo.getText().trim();
    String contraseña = new String(txtcontrase.getPassword()).trim();

    String resultado = objetoLogin.validarLogin(correo, contraseña);

    if (resultado != null) {
        // Login exitoso
        javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido, " + resultado + "!");
         pantallaPrincipal.actualizarNombreUsuario(resultado);

    } else {
        // Login fallido
        javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error de autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

       
    }//GEN-LAST:event_btnentrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtcontrase;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
