/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Dao.DaoProductos;
import Formularios.Entradas;
import Formularios.Salidas;
import Modelo.productos;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tadeo
 */
public class BuscaProductos extends javax.swing.JFrame {

DefaultTableModel modelo=new DefaultTableModel();
productos p=new productos();
DaoProductos dao=new DaoProductos();
public static boolean tipo;

    /**
     * Creates new form BuscaEntradas
     */
    public BuscaProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        listarProductos();
    }

    private void listarProductos(){
        List<productos> lista=dao.Listar();
        modelo=(DefaultTableModel) prodcutos.getModel();
        Object[] ob=new Object[4];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdproducto();
            ob[1]=lista.get(i).getNomProd();
            ob[2]=lista.get(i).getStock();
            ob[3]=lista.get(i).getPrecioV();
            modelo.addRow(ob);
        }
       prodcutos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound2 = new Modelo.JpanelRound();
        jpanelRound3 = new Modelo.JpanelRound();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jpanelRound4 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodcutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 970));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound2.setBackground(new java.awt.Color(51, 153, 255));
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound3.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, -1));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound3.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 200, -1));

        txtprecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound3.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 200, -1));

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jpanelRound3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 110, 30));

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/ic_send_128_28719.png"))); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jpanelRound3.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, 30));

        jpanelRound2.add(jpanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 780, 270));

        jpanelRound4.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodcutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock", "Precio"
            }
        ));
        prodcutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodcutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodcutos);

        jpanelRound4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 310));

        jpanelRound2.add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 780, 310));

        getContentPane().add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodcutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodcutosMouseClicked
        // TODO add your handling code here:
        int fila=prodcutos.getSelectedRow();
        txtid.setText(prodcutos.getValueAt(fila, 0).toString());
        txtnombre.setText(prodcutos.getValueAt(fila, 1).toString());
        txtstock.setText(prodcutos.getValueAt(fila, 2).toString());
        txtprecio.setText(prodcutos.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_prodcutosMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
         dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(tipo==true){
        Salidas.txtidProducto.setText(txtid.getText());
        Salidas.txtprecio.setText(txtprecio.getText());
        Salidas.txtproducto.setText(txtnombre.getText());
        Salidas.txtstock.setText(txtstock.getText());
       }else{
        Entradas.txtnombreP.setText(txtnombre.getText());
        Entradas.txtprecioV.setText(txtprecio.getText());
        Entradas.txtidProducto.setText(txtid.getText());
        Entradas.idpNuevo=Integer.parseInt(txtid.getText());
       }
        dispose();
    }//GEN-LAST:event_btnEnviarActionPerformed
                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound3;
    private Modelo.JpanelRound jpanelRound4;
    private javax.swing.JTable prodcutos;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
