/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoClientes;
import Modelo.clientes;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class Clientes extends javax.swing.JPanel {
clientes c=new clientes();
    DaoClientes dao=new DaoClientes();
    DefaultTableModel modeloClientes=new DefaultTableModel();
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
         listarClientes();
    }
private void listarClientes(){
        List<clientes> lista=dao.Listar();
        modeloClientes=(DefaultTableModel) tablaclientes.getModel();
        Object[] ob=new Object[7];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdCliente();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getApellido();
            ob[3]=lista.get(i).getDocumento();
            ob[4]=lista.get(i).getDireccion();
            ob[5]=lista.get(i).getTelefono();
            ob[6]=lista.get(i).getCorreo();
            modeloClientes.addRow(ob);
        }
       tablaclientes.setModel(modeloClientes);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound4 = new Modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound5 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        lblGestionClientes = new rojeru_san.rslabel.RSLabelBorderRound();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound4.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound4.setRoundBottomLeft(35);
        jpanelRound4.setRoundBottomRight(35);
        jpanelRound4.setRoundTopLeft(35);
        jpanelRound4.setRoundTopRight(35);
        jpanelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        jpanelRound4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        jpanelRound4.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 246, -1));

        jLabel3.setText("Nombre");
        jpanelRound4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));
        jpanelRound4.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 246, -1));

        jLabel5.setText("Apellido");
        jpanelRound4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, -1, -1));
        jpanelRound4.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 246, -1));

        jLabel6.setText("Cedula");
        jpanelRound4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, -1, -1));
        jpanelRound4.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, 162, -1));

        jLabel7.setText("Direccion");
        jpanelRound4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jpanelRound4.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 246, -1));

        jLabel8.setText("Telefono");
        jpanelRound4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jpanelRound4.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 246, -1));

        jLabel9.setText("Correo");
        jpanelRound4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        jpanelRound4.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 246, -1));

        btnEliminar.setBackground(new java.awt.Color(204, 255, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, 30));

        btnEditar.setBackground(new java.awt.Color(204, 255, 204));
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 30));

        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 40, 40));

        add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 540));

        jpanelRound5.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound5.setRoundBottomLeft(35);
        jpanelRound5.setRoundBottomRight(35);
        jpanelRound5.setRoundTopLeft(35);
        jpanelRound5.setRoundTopRight(35);

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cedula", "Direccion", "Telefono", "Correo"
            }
        ));
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclientes);

        javax.swing.GroupLayout jpanelRound5Layout = new javax.swing.GroupLayout(jpanelRound5);
        jpanelRound5.setLayout(jpanelRound5Layout);
        jpanelRound5Layout.setHorizontalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound5Layout.setVerticalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jpanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 550, 510));

        lblGestionClientes.setText("Gestion De Clientes");
        lblGestionClientes.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        add(lblGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 650, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        // TODO add your handling code here:
        int fila = tablaclientes.getSelectedRow();
        if (fila != -1) { 
        txtidcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaclientes.getValueAt(fila, 1).toString());
        txtapellido.setText(tablaclientes.getValueAt(fila, 2).toString());
        txtdocumento.setText(tablaclientes.getValueAt(fila, 3).toString());
        txtdireccion.setText(tablaclientes.getValueAt(fila, 4).toString());
        txttelefono.setText(tablaclientes.getValueAt(fila, 5).toString());
        txtcorreo.setText(tablaclientes.getValueAt(fila, 6).toString());
    } else {
        JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fila.");
    }


    }//GEN-LAST:event_tablaclientesMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       if (txtnombre.getText().trim().isEmpty() ||
        txtapellido.getText().trim().isEmpty() ||
        txtdocumento.getText().trim().isEmpty() ||
        txtdireccion.getText().trim().isEmpty() ||
        txttelefono.getText().trim().isEmpty() ||
        txtcorreo.getText().trim().isEmpty()) {
        
        JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        return;
    }

    
    if (!txtcorreo.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(null, "Correo no válido.");
        return;
    }

    
    if (!txttelefono.getText().trim().matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El teléfono debe contener solo números.");
        return;
    }

    
    c.setNombre(txtnombre.getText().trim());
    c.setApellido(txtapellido.getText().trim());
    c.setDocumento(txtdocumento.getText().trim());
    c.setDireccion(txtdireccion.getText().trim());
    c.setTelefono(txttelefono.getText().trim());
    c.setCorreo(txtcorreo.getText().trim());

   
    if (dao.insertar(c)) {
        JOptionPane.showMessageDialog(null, "Cliente registrado con éxito.");
        limpiarCampos();
        limpiarTablaCLientes();
        listarClientes();
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo registrar el cliente.");
    }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     int fila = tablaclientes.getSelectedRow();
if (fila == -1 && txtidcliente.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Seleccione un cliente de la tabla o ingrese un ID válido.");
    return;
}
if (txtnombre.getText().trim().isEmpty() ||
    txtapellido.getText().trim().isEmpty() ||
    txtdocumento.getText().trim().isEmpty() ||
    txtdireccion.getText().trim().isEmpty() ||
    txttelefono.getText().trim().isEmpty() ||
    txtcorreo.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
    return;
}
if (!txtcorreo.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
    JOptionPane.showMessageDialog(null, "Correo no válido.");
    return;
}
try {
    c.setIdCliente(Integer.parseInt(txtidcliente.getText().trim()));
    c.setNombre(txtnombre.getText().trim());
    c.setApellido(txtapellido.getText().trim());
    c.setDocumento(txtdocumento.getText().trim());
    c.setDireccion(txtdireccion.getText().trim());
    c.setTelefono(txttelefono.getText().trim());
    c.setCorreo(txtcorreo.getText().trim());

    if (dao.editar(c)) {
        JOptionPane.showMessageDialog(null, "Cliente modificado con éxito.");
        limpiarTablaCLientes();
        listarClientes();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo modificar el cliente.");
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
}
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (!txtidcliente.getText().trim().isEmpty()) {
    try {
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro de eliminar el cliente?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            c.setIdCliente(Integer.parseInt(txtidcliente.getText().trim()));
            
            if (dao.eliminar(c)) {
                limpiarTablaCLientes();
                listarClientes();
                limpiarCampos();
                JOptionPane.showMessageDialog(null, "Cliente eliminado con éxito.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente.");
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID del cliente debe ser un número válido.");
    }
} else {
    JOptionPane.showMessageDialog(null, "Seleccione un cliente primero.");
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String documento = txtdocumento.getText().trim();

if (documento.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Ingrese el número de documento.");
    return;
}


if (!documento.matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "El documento debe contener solo números.");
    return;
}

c.setDocumento(documento);

if (dao.buscar(c)) {
    txtidcliente.setText(String.valueOf(c.getIdCliente()));
    txtnombre.setText(c.getNombre());
    txtapellido.setText(c.getApellido());
    txtdocumento.setText(c.getDocumento());
    txtdireccion.setText(c.getDireccion());
    txttelefono.setText(c.getTelefono());
    txtcorreo.setText(c.getCorreo());
} else {
    JOptionPane.showMessageDialog(null, "El cliente no existe.");
    limpiarCampos();
}

    }//GEN-LAST:event_btnBuscarActionPerformed
void limpiarCampos(){
        txtidcliente.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
    }
    
    void limpiarTablaCLientes(){
        for(int i=0;i<modeloClientes.getRowCount();i++){
            modeloClientes.removeRow(i);
            i=0-1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound4;
    private Modelo.JpanelRound jpanelRound5;
    private rojeru_san.rslabel.RSLabelBorderRound lblGestionClientes;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
