/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoClientes;
import Dao.conexion;

import Modelo.clientes;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Adrian
 */
public class Clientes extends javax.swing.JPanel {
clientes c=new clientes();
    DaoClientes dao=new DaoClientes();
    DefaultTableModel modeloClientes=new DefaultTableModel();
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
         listarClientes();
    }
private void listarClientes(){
        List<clientes> lista=dao.Listar();
        modeloClientes=(DefaultTableModel) tablaclientes.getModel();
        Object[] ob=new Object[7];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdCliente();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getApellido();
            ob[3]=lista.get(i).getDocumento();
            ob[4]=lista.get(i).getDireccion();
            ob[5]=lista.get(i).getTelefono();
            ob[6]=lista.get(i).getCorreo();
            modeloClientes.addRow(ob);
        }
       tablaclientes.setModel(modeloClientes);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound4 = new Modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnPdf = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound5 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        lblGestionClientes = new rojeru_san.rslabel.RSLabelBorderRound();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1270, 970));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound4.setBackground(new java.awt.Color(102, 204, 255));
        jpanelRound4.setRoundBottomLeft(35);
        jpanelRound4.setRoundBottomRight(35);
        jpanelRound4.setRoundTopLeft(35);
        jpanelRound4.setRoundTopRight(35);
        jpanelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jpanelRound4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtidcliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound4.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jpanelRound4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound4.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        jpanelRound4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound4.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 320, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cedula");
        jpanelRound4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtdocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jpanelRound4.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        jpanelRound4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound4.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 320, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Teléfono");
        jpanelRound4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txttelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound4.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 320, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");
        jpanelRound4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        jpanelRound4.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 320, -1));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, 30));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_upgrade_recyclearrows_arrow_azul_12426 (1).png"))); // NOI18N
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 480, -1, 30));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/1486564412-plus_81511 (1).png"))); // NOI18N
        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 30));

        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 40, 40));

        btnPdf.setBackground(new java.awt.Color(213, 137, 137));
        btnPdf.setBackgroundHover(new java.awt.Color(14, 76, 117));
        btnPdf.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_DRIVE_FILE);
        btnPdf.setRound(25);
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        jpanelRound4.add(btnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 50, -1));

        add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 540));

        jpanelRound5.setBackground(new java.awt.Color(102, 204, 255));
        jpanelRound5.setRoundBottomLeft(35);
        jpanelRound5.setRoundBottomRight(35);
        jpanelRound5.setRoundTopLeft(35);
        jpanelRound5.setRoundTopRight(35);

        tablaclientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cedula", "Dirección ", "Teléfono ", "Correo"
            }
        ));
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclientes);

        javax.swing.GroupLayout jpanelRound5Layout = new javax.swing.GroupLayout(jpanelRound5);
        jpanelRound5.setLayout(jpanelRound5Layout);
        jpanelRound5Layout.setHorizontalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound5Layout.setVerticalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jpanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 550, 550));

        lblGestionClientes.setBorder(null);
        lblGestionClientes.setText("Gestión De Clientes");
        lblGestionClientes.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        add(lblGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 510, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        // TODO add your handling code here:
        int fila = tablaclientes.getSelectedRow();
        if (fila != -1) { 
        txtidcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaclientes.getValueAt(fila, 1).toString());
        txtapellido.setText(tablaclientes.getValueAt(fila, 2).toString());
        txtdocumento.setText(tablaclientes.getValueAt(fila, 3).toString());
        txtdireccion.setText(tablaclientes.getValueAt(fila, 4).toString());
        txttelefono.setText(tablaclientes.getValueAt(fila, 5).toString());
        txtcorreo.setText(tablaclientes.getValueAt(fila, 6).toString());
    } else {
        JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fila.");
    }


    }//GEN-LAST:event_tablaclientesMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       if (txtnombre.getText().trim().isEmpty() ||
        txtapellido.getText().trim().isEmpty() ||
        txtdocumento.getText().trim().isEmpty() ||
        txtdireccion.getText().trim().isEmpty() ||
        txttelefono.getText().trim().isEmpty() ||
        txtcorreo.getText().trim().isEmpty()) {
        
        JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        return;
    }

    
    if (!txtcorreo.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(null, "Correo no válido.");
        return;
    }

    
    if (!txttelefono.getText().trim().matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "El teléfono debe contener solo números.");
        return;
    }

    
    c.setNombre(txtnombre.getText().trim());
    c.setApellido(txtapellido.getText().trim());
    c.setDocumento(txtdocumento.getText().trim());
    c.setDireccion(txtdireccion.getText().trim());
    c.setTelefono(txttelefono.getText().trim());
    c.setCorreo(txtcorreo.getText().trim());

   
    if (dao.insertar(c)) {
        JOptionPane.showMessageDialog(null, "Cliente registrado con éxito.");
        limpiarCampos();
        limpiarTablaCLientes();
        listarClientes();
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo registrar el cliente.");
    }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     int fila = tablaclientes.getSelectedRow();
if (fila == -1 && txtidcliente.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Seleccione un cliente de la tabla o ingrese un ID válido.");
    return;
}
if (txtnombre.getText().trim().isEmpty() ||
    txtapellido.getText().trim().isEmpty() ||
    txtdocumento.getText().trim().isEmpty() ||
    txtdireccion.getText().trim().isEmpty() ||
    txttelefono.getText().trim().isEmpty() ||
    txtcorreo.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
    return;
}
if (!txtcorreo.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
    JOptionPane.showMessageDialog(null, "Correo no válido.");
    return;
}
try {
    c.setIdCliente(Integer.parseInt(txtidcliente.getText().trim()));
    c.setNombre(txtnombre.getText().trim());
    c.setApellido(txtapellido.getText().trim());
    c.setDocumento(txtdocumento.getText().trim());
    c.setDireccion(txtdireccion.getText().trim());
    c.setTelefono(txttelefono.getText().trim());
    c.setCorreo(txtcorreo.getText().trim());

    if (dao.editar(c)) {
        JOptionPane.showMessageDialog(null, "Cliente modificado con éxito.");
        limpiarTablaCLientes();
        listarClientes();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo modificar el cliente.");
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
}
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (!txtidcliente.getText().trim().isEmpty()) {
    try {
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro de eliminar el cliente?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            c.setIdCliente(Integer.parseInt(txtidcliente.getText().trim()));
            
            if (dao.eliminar(c)) {
                limpiarTablaCLientes();
                listarClientes();
                limpiarCampos();
                JOptionPane.showMessageDialog(null, "Cliente eliminado con éxito.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente.");
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID del cliente debe ser un número válido.");
    }
} else {
    JOptionPane.showMessageDialog(null, "Seleccione un cliente primero.");
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String documento = txtdocumento.getText().trim();

if (documento.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Ingrese el número de documento.");
    return;
}


if (!documento.matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "El documento debe contener solo números.");
    return;
}

c.setDocumento(documento);

if (dao.buscar(c)) {
    txtidcliente.setText(String.valueOf(c.getIdCliente()));
    txtnombre.setText(c.getNombre());
    txtapellido.setText(c.getApellido());
    txtdocumento.setText(c.getDocumento());
    txtdireccion.setText(c.getDireccion());
    txttelefono.setText(c.getTelefono());
    txtcorreo.setText(c.getCorreo());
} else {
    JOptionPane.showMessageDialog(null, "El cliente no existe.");
    limpiarCampos();
}

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
          String correo = txtcorreo.getText().trim();
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
             JOptionPane.showMessageDialog(null, "⚠ Correo no válido. Ejemplo: ejemplo@dominio.com");
            txtcorreo.requestFocus(); // Vuelve al campo
        }
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // 
            Toolkit.getDefaultToolkit().beep();}
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
//RegenerarJasper();
    
//// TODO add your handling code here:
       GenerarPDF();
      //CrearReporteBasico();
      // JasperPrint reporteTodoProducto(); 
    //String rutaReporte = "src/reportes/reporteClientes.jasper";
    //String salidaPDF = "C://";  // Puedes cambiar esta ruta

    // Si no tienes parámetros, solo crea un mapa vacío
   // Map<String, Object> parametros = new HashMap<>();
//ReporteFacturaSalida r = new ReporteFacturaSalida();
//r.generarReporteSalida("001-123");
    // Si el reporte necesita parámetros, agrégalos así:
    // parametros.put("id_usuario", 5);

    // Llamada al método
    //ReportePDF.generarReporte(rutaReporte, parametros, salidaPDF);

    }//GEN-LAST:event_btnPdfActionPerformed


private final Connection conection=new conexion().conectar();



    void GenerarPDF(){
        Map p=new HashMap();
        JasperReport report;
        JasperPrint print;

        try{
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/reportes/reporteClientes.jrxml");
            print=JasperFillManager.fillReport(report,p, conection);
            JasperViewer view=new JasperViewer(print,false);
            view.setTitle("Lista De Clientes");
            view.setVisible(true);
        }catch(JRException e){
            e.printStackTrace();
        }
    }
  
    void limpiarCampos(){
        txtidcliente.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
    }
    
    void limpiarTablaCLientes(){
        for(int i=0;i<modeloClientes.getRowCount();i++){
            modeloClientes.removeRow(i);
            i=0-1;
        }
    }
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private RSMaterialComponent.RSButtonMaterialIconDos btnPdf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound4;
    private Modelo.JpanelRound jpanelRound5;
    private rojeru_san.rslabel.RSLabelBorderRound lblGestionClientes;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
