/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

//import Dao.DaoCategoria;

import Dao.DaoCategoria;
import Dao.DaoEntradas;
import Dao.DaoProductos;
import Dao.DaoProveedor;
import Modelo.Categoria;
import Modelo.entradas;
import Modelo.productos;
import Modelo.proveedor;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class Entradas extends javax.swing.JPanel {
entradas e=new entradas();
    Categoria ct=new Categoria();
    proveedor pr=new proveedor();
    productos p=new productos();
    DaoProductos daoPr=new DaoProductos();
    DaoEntradas dao=new DaoEntradas();
    DaoCategoria daoC=new DaoCategoria();
    DaoProveedor daoP=new DaoProveedor();
    DefaultTableModel modelo=new DefaultTableModel();
    public static int idpNuevo;
    public static int idpOld;
    public static int cant;

    
    /**
     * Creates new form Entradas
     */
    public Entradas() {
        initComponents();
       listarEntradas();
    }

    private void listarEntradas(){
        List<entradas> lista=dao.Listar();
        modelo=(DefaultTableModel) tablaEntradas.getModel();
        Object[] ob=new Object[8];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdentrada();
            ob[1]=lista.get(i).getIdproducto();
            ob[2]=lista.get(i).getStock();
            ob[3]=lista.get(i).getFecha();
            ob[4]=lista.get(i).getIdproveedor();
            ob[5]=lista.get(i).getPrecioE();
            ob[6]=lista.get(i).getPrecioV();
            ob[7]=lista.get(i).getTotal();
            modelo.addRow(ob);
        }
       tablaEntradas.setModel(modelo);
    }

   void numProducto(){
        int numero=daoPr.numProducto();
        if(numero==0){
        txtidProducto.setText("1");
       }else{
       int i=numero;
        i=i+1;
       txtidProducto.setText(i+"");
        
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonMaterialIconDos1 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound1 = new Modelo.JpanelRound();
        jpanelRound2 = new Modelo.JpanelRound();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtprecioV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtprecioE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombreP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtidentrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jpanelRound3 = new Modelo.JpanelRound();
        jLabel11 = new javax.swing.JLabel();
        txtidProducto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        jpanelRound4 = new Modelo.JpanelRound();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtidproveedor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JTextField();
        btnBuscarProvedorr = new javax.swing.JButton();
        jpanelRound5 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnElimnar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        rSButtonMaterialIconDos1.setText("rSButtonMaterialIconDos1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound1.setBackground(new java.awt.Color(102, 204, 255));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound2.setRoundBottomLeft(25);
        jpanelRound2.setRoundBottomRight(25);
        jpanelRound2.setRoundTopLeft(25);
        jpanelRound2.setRoundTopRight(25);
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Total");
        jpanelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtprecioV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtprecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Precio Venta");
        jpanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtprecioE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprecioE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecioEKeyReleased(evt);
            }
        });
        jpanelRound2.add(txtprecioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Precio Entrada.");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Fecha");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstockKeyReleased(evt);
            }
        });
        jpanelRound2.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Stock");
        jpanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtnombreP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtnombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Nombre Producto");
        jpanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtidentrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtidentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("ID Entrada");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        dateFecha.setFocusable(false);
        dateFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, -1));

        jpanelRound1.add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 430));

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound3.setRoundBottomLeft(25);
        jpanelRound3.setRoundBottomRight(25);
        jpanelRound3.setRoundTopLeft(25);
        jpanelRound3.setRoundTopRight(25);

        jLabel11.setText("ID Producto");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 43, 153));
        jLabel18.setText("Bucar Producto");

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnBuscarProducto))
                    .addComponent(jLabel18)
                    .addComponent(jLabel11))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpanelRound1.add(jpanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 240, 140));

        jpanelRound4.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound4.setRoundBottomLeft(25);
        jpanelRound4.setRoundBottomRight(25);
        jpanelRound4.setRoundTopLeft(25);
        jpanelRound4.setRoundTopRight(25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 173, 61));
        jLabel21.setText("Datos del Proveedor");

        jLabel20.setText("ID");

        jLabel19.setText("Nombre");

        btnBuscarProvedorr.setText("Buscar");
        btnBuscarProvedorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProvedorrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound4Layout = new javax.swing.GroupLayout(jpanelRound4);
        jpanelRound4.setLayout(jpanelRound4Layout);
        jpanelRound4Layout.setHorizontalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanelRound4Layout.createSequentialGroup()
                        .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanelRound4Layout.createSequentialGroup()
                        .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRound4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(btnBuscarProvedorr)
                        .addGap(15, 15, 15))))
        );
        jpanelRound4Layout.setVerticalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(btnBuscarProvedorr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jpanelRound1.add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 270, 140));

        jpanelRound5.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound5.setRoundBottomLeft(25);
        jpanelRound5.setRoundBottomRight(25);
        jpanelRound5.setRoundTopLeft(25);
        jpanelRound5.setRoundTopRight(25);

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Stock", "Fecha", "IDProveedor", "Precio E", "Precio V", "Total"
            }
        ));
        tablaEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEntradasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEntradas);

        javax.swing.GroupLayout jpanelRound5Layout = new javax.swing.GroupLayout(jpanelRound5);
        jpanelRound5.setLayout(jpanelRound5Layout);
        jpanelRound5Layout.setHorizontalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound5Layout.setVerticalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jpanelRound1.add(jpanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 550, 340));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        btnElimnar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnElimnar.setText("Eliminar");
        btnElimnar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimnarActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnElimnar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion De stock");
        jpanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 460, 50));

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEntradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEntradasMouseClicked
     int fila=tablaEntradas.getSelectedRow();
        txtidentrada.setText(tablaEntradas.getValueAt(fila, 0).toString());
        txtidProducto.setText(tablaEntradas.getValueAt(fila, 1).toString());
        txtstock.setText(tablaEntradas.getValueAt(fila, 2).toString());
        dateFecha.setDate(Date.valueOf(tablaEntradas.getValueAt(fila, 3).toString()));
        txtidproveedor.setText(tablaEntradas.getValueAt(fila, 4).toString());
        txtprecioE.setText(tablaEntradas.getValueAt(fila, 5).toString());
        txtprecioV.setText(tablaEntradas.getValueAt(fila, 6).toString());
        txtTotal.setText(tablaEntradas.getValueAt(fila, 7).toString());

        
        pr.setIdProveedor(Integer.parseInt(txtidproveedor.getText()));
        if(daoP.buscar(pr)){
            txtproveedor.setText(pr.getActivadad_comercial() );
        }else{
            txtproveedor.setText("Error");
        }
        p.setIdproducto(Integer.parseInt(txtidProducto.getText()));
        if(daoPr.buscar(p)){
           txtnombreP.setText(p.getNomProd());
        }else{
            txtproveedor.setText("Error");
        }
        idpOld=Integer.parseInt(txtidProducto.getText());
        cant=Integer.parseInt(txtstock.getText());
        idpNuevo=Integer.parseInt(txtidProducto.getText());
    }//GEN-LAST:event_tablaEntradasMouseClicked

    private void txtprecioEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioEKeyReleased
        // TODO add your handling code here:
        double cant,precio;
        if(!txtstock.getText().isEmpty()){
            cant=Double.parseDouble(txtstock.getText());
            precio=Double.parseDouble(txtprecioE.getText());
            txtTotal.setText(cant*precio+"");
        }else{
        }
    }//GEN-LAST:event_txtprecioEKeyReleased

    private void txtstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyReleased
        // TODO add your handling code here:
        double cant,precio;
        if(!txtprecioE.getText().isEmpty()){
            cant=Double.parseDouble(txtstock.getText());
            precio=Double.parseDouble(txtprecioE.getText());
            txtTotal.setText(cant*precio+"");
        }else{
        }
    }//GEN-LAST:event_txtstockKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    Calendar cal;
            int d,m,a;
            cal=dateFecha.getCalendar();
            d=cal.get(Calendar.DAY_OF_MONTH);
            m=cal.get(Calendar.MONTH);
            a=cal.get(Calendar.YEAR)-1900;
            e.setIdproducto(Integer.parseInt(txtidProducto.getText()));
            e.setStock(Integer.parseInt(txtstock.getText()));
            e.setFecha(new Date(a,m,d));
            e.setIdproveedor(Integer.parseInt(txtidproveedor.getText()));
            e.setPrecioE(Double.parseDouble(txtprecioE.getText()));
            e.setPrecioV(Double.parseDouble(txtprecioV.getText()));
            e.setTotal(Double.parseDouble(txtTotal.getText()));
            p.setIdproducto(Integer.parseInt(txtidProducto.getText()));
            p.setPrecioV(Double.parseDouble(txtprecioV.getText()));
            if(dao.insertar(e)&&daoPr.sumarStock(Integer.parseInt(txtidProducto.getText()), Integer.parseInt(txtstock.getText()))&&daoPr.editarPrecioV(p)){
              
               JOptionPane.showMessageDialog(null,"Entrada Registrada Con Exito");
            }else{
              
             JOptionPane.showMessageDialog(null,"No se pudo registrar la entrada");
            }
            limpiarCampos();
        limpiarTablaEntradas();
        listarEntradas();
        numProducto();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     int fila=tablaEntradas.getSelectedRow();
        if(fila==-1&&txtidentrada.getText().isEmpty()){
          
          JOptionPane.showMessageDialog(null,"Seleccione una Entrada");
        }else{
            int cantNueva;
            cantNueva=Integer.parseInt(txtstock.getText()); 
            Calendar cal;
            int d,m,a;
            cal=dateFecha.getCalendar();
            d=cal.get(Calendar.DAY_OF_MONTH);
            m=cal.get(Calendar.MONTH);
            a=cal.get(Calendar.YEAR)-1900;
            e.setIdproducto(Integer.parseInt(txtidProducto.getText()));
            e.setStock(Integer.parseInt(txtstock.getText()));
            e.setFecha(new Date(a,m,d));
            e.setIdproveedor(Integer.parseInt(txtidproveedor.getText()));
            e.setPrecioE(Double.parseDouble(txtprecioE.getText()));
            e.setPrecioV(Double.parseDouble(txtprecioV.getText()));
            e.setTotal(Double.parseDouble(txtTotal.getText()));
            e.setIdentrada(Integer.parseInt(txtidentrada.getText()));
 
            DaoProductos daoPro=new DaoProductos();
            if(dao.editar(e)){
                 if(idpOld==idpNuevo){
                    if(cantNueva>cant){
                       int c=cantNueva-cant;
                        if(daoPro.sumarStock(idpOld, c)){ 
                        }
                    }else{
                         int c=cant-cantNueva;
                       if(daoPro.restarStock(idpOld, c)){
                        }
                    }
                }else{
                daoPro.restarStock(idpOld, cant);
                daoPro.sumarStock(idpNuevo, Integer.parseInt(txtstock.getText()));
                }
               
               JOptionPane.showMessageDialog(null,"Se modifico con exito");
                limpiarCampos();
                limpiarTablaEntradas();
                listarEntradas();
            }else{
              
                JOptionPane.showMessageDialog(null,"Erorr al modificar la entrada");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnElimnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimnarActionPerformed
        if(!txtidentrada.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar la entrada?","Confirmar",2);
            if(confirmacion==0){
                e.setIdentrada(Integer.parseInt(txtidentrada.getText()));
                dao.buscar(e);
                int idP=e.getIdproducto();
                int cant=e.getStock();
                daoPr.restarStock(idP, cant);
                dao.eliminar(e);
                limpiarCampos();
                limpiarTablaEntradas();
                listarEntradas();
              
             JOptionPane.showMessageDialog(null,"Se Elimino con exito La Entrada");
            }
        }else{
          
        JOptionPane.showMessageDialog(null,"Seleccione una Entrada");
        }
    }//GEN-LAST:event_btnElimnarActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
       BuscaProductos.tipo=false;
        BuscaProductos m=new BuscaProductos();
     m.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarProvedorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProvedorrActionPerformed
      BuscarDato.tipo=false;
       BuscarDato m=new BuscarDato();
       m.setVisible(true);
    }//GEN-LAST:event_btnBuscarProvedorrActionPerformed

 void limpiarCampos(){
        txtidentrada.setText("");
        txtnombreP.setText("");
        txtstock.setText("");
        txtprecioE.setText("");
        txtprecioV.setText("");
        txtTotal.setText("");
        txtproveedor.setText("");
        txtproveedor.setText("");
    }
    
    void limpiarTablaEntradas(){
        for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }

   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProvedorr;
    private javax.swing.JButton btnElimnar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound3;
    private Modelo.JpanelRound jpanelRound4;
    private Modelo.JpanelRound jpanelRound5;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos1;
    private javax.swing.JTable tablaEntradas;
    private javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtidentrada;
    public static javax.swing.JTextField txtidproveedor;
    public static javax.swing.JTextField txtnombreP;
    private javax.swing.JTextField txtprecioE;
    public static javax.swing.JTextField txtprecioV;
    public static javax.swing.JTextField txtproveedor;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
