/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoDetalleSalida;
import Dao.DaoProductos;
import Dao.DaoSalida;
import Modelo.detalleSalida;
import Modelo.productos;
import Modelo.salidas;
import com.toedter.calendar.JDateChooser;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class ListaSalidas extends javax.swing.JPanel {
DefaultTableModel modelo=new DefaultTableModel();
DaoSalida dao=new DaoSalida();
salidas s=new salidas();

detalleSalida ds=new detalleSalida();
DaoDetalleSalida daoDs=new DaoDetalleSalida();
DefaultTableModel modelodt=new DefaultTableModel();

productos p=new productos();
DaoProductos daoP=new DaoProductos();


    /**
     * Creates new form ListaSalidas
     */
    public ListaSalidas() {
        initComponents();
        listarSalidas();
    }

    private void listarSalidas(){
        List<salidas> lista=dao.Listar();
        modelo=(DefaultTableModel) tablaSalidas.getModel();
        Object[] ob=new Object[8];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdSalida();
            ob[1]=lista.get(i).getNumSalida();
            ob[2]=lista.get(i).getIdCliente();
            ob[3]=lista.get(i).getFecha();
            ob[4]=lista.get(i).getSubtotal();
            ob[5]=lista.get(i).getIgv();
            ob[6]=lista.get(i).getTotal();
            ob[7]=lista.get(i).getEstado();
            modelo.addRow(ob);
        }
       tablaSalidas.setModel(modelo);
    }

    private void listarSalidasPorFecha(String fecha1,String fecha2){
        List<salidas> lista=dao.ListarPorFecha(fecha1, fecha2);
        modelo=(DefaultTableModel) tablaSalidas.getModel();
        Object[] ob=new Object[8];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdSalida();
            ob[1]=lista.get(i).getNumSalida();
            ob[2]=lista.get(i).getIdCliente();
            ob[3]=lista.get(i).getFecha();
            ob[4]=lista.get(i).getSubtotal();
            ob[5]=lista.get(i).getIgv();
            ob[6]=lista.get(i).getTotal();
            ob[7]=lista.get(i).getEstado();
            modelo.addRow(ob);
        }
       tablaSalidas.setModel(modelo);
    }

    private void listarDetalle(int idS){
        List<detalleSalida> lista=daoDs.buscar(idS);
        modelodt=(DefaultTableModel) tablaDetalle.getModel();
        Object[] ob=new Object[2];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdEntrada();
            ob[1]=lista.get(i).getCantidad();
            modelodt.addRow(ob);
        }
       tablaDetalle.setModel(modelodt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jpanelRound2 = new Modelo.JpanelRound();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnumSalida = new javax.swing.JTextField();
        btnBuscarPedido = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fechainicial = new com.toedter.calendar.JDateChooser();
        fechafinal = new com.toedter.calendar.JDateChooser();
        txtidSalida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpanelRound3 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpanelRound4 = new Modelo.JpanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound1.setBackground(new java.awt.Color(102, 204, 255));
        jpanelRound1.setPreferredSize(new java.awt.Dimension(982, 775));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpanelRound1.add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 670, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Numero:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl.setText("idSalida");
        jPanel3.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("fecha Inicial:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Fecha Final:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));
        jPanel3.add(txtnumSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));

        btnBuscarPedido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscarPedido.setText("Buscar Pedido");
        btnBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 150, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar Pedido");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        jPanel3.add(fechainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, -1));
        jPanel3.add(fechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 190, -1));
        jPanel3.add(txtidSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Aprobar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, -1));

        jpanelRound1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 570, 202));

        jpanelRound3.setBackground(new java.awt.Color(204, 204, 204));

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Numero", "Id Cliente", "fecha", "subtotal", "IGV", "Total", "Estado"
            }
        ));
        tablaSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSalidas);

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelRound1.add(jpanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pedidos");
        jpanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jpanelRound4.setBackground(new java.awt.Color(204, 204, 204));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Prod", "Cant"
            }
        ));
        tablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDetalle);

        javax.swing.GroupLayout jpanelRound4Layout = new javax.swing.GroupLayout(jpanelRound4);
        jpanelRound4.setLayout(jpanelRound4Layout);
        jpanelRound4Layout.setHorizontalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound4Layout.setVerticalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpanelRound1.add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 274, -1, -1));

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidasMouseClicked
        // TODO add your handling code here:
        int fila=tablaSalidas.getSelectedRow();
        String num=tablaSalidas.getValueAt(fila, 1).toString();
      txtnumSalida.setText(num);
      lbl.setText(tablaSalidas.getValueAt(fila, 0).toString());
        int idsalida=Integer.parseInt(tablaSalidas.getValueAt(fila, 0).toString());

        limpiarTablaDT();
        listarDetalle(idsalida);
    }//GEN-LAST:event_tablaSalidasMouseClicked

    private void tablaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDetalleMouseClicked

    private void btnBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedidoActionPerformed
      /* limpiarTabla();
        
        String fecha1=obtenerFechas(fechainicial)+"";
        String fecha2=obtenerFechas(fechafinal)+"";
        listarSalidasPorFecha(fecha1,fecha2);*/
    }//GEN-LAST:event_btnBuscarPedidoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
  /*       int fila = tablaSalidas.getSelectedRow();
    if (fila == -1 && txtnumSalida.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Seleccione una salida de la tabla o ingrese un número de salida");
    } else {
        try {
            int idSalida = getSelectedSalidaId(); // Método que explico abajo
            s.setIdSalida(idSalida);
            s.setEstado("Anulada");

            if (dao.anularSalida(s)) {
                limpiarTabla();
                listarSalidas();
                limpiarCampos();
                sumarStock();
                limpiarTablaDT();
                JOptionPane.showMessageDialog(null, "Salida anulada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(null, " No se pudo anular la salida.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al procesar: " + e.getMessage());
        }
    }
*/
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /*    int fila = tablaSalidas.getSelectedRow();
    if (fila == -1 && txtnumSalida.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Seleccione una salida o ingrese el número de salida");
    } else {
        try {
            int idSalida = getSelectedSalidaId(); // Método compartido
            s.setIdSalida(idSalida);
            s.setEstado("Aprobada");

            if (dao.aprobarSalida(s)) {
                limpiarTabla();
                listarSalidas();
                limpiarCampos();
                limpiarTablaDT();
                JOptionPane.showMessageDialog(null, "✅ Salida aprobada con éxito.");
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se pudo aprobar la salida.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    
}*/
    }//GEN-LAST:event_jButton1ActionPerformed

   void limpiarTabla(){
        for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }
    void limpiarTablaDT(){
        for(int i=0;i<modelodt.getRowCount();i++){
            modelodt.removeRow(i);
            i=0-1;
        }
    }

    public Date obtenerFechas(JDateChooser dch){
        Calendar cal;
        int d,m,a;
        cal=dch.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        return new Date(a,m,d);
}
/*
    void sumarStock(){
        for(int i=0;i<tablaDetalle.getRowCount();i++){
        int idProducto=Integer.parseInt(tablaDetalle.getValueAt(i, 0).toString());
        int cant=Integer.parseInt(tablaDetalle.getValueAt(i, 1).toString());
        daoP.sumarStock(idProducto, cant);
        }
    }*/

    private void limpiarCampos() {
        txtnumSalida.setText("");
txtidSalida.setText("");
    }
private int getSelectedSalidaId() throws Exception {
    int fila = tablaSalidas.getSelectedRow();
    if (fila != -1) {
        return Integer.parseInt(tablaSalidas.getValueAt(fila, 0).toString()); // columna 0 = idSalida
    } else if (!txtidSalida.getText().isEmpty()) {
        return Integer.parseInt(txtidSalida.getText());
    } else {
        throw new Exception("No se pudo obtener el ID de salida");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnCancelar;
    private com.toedter.calendar.JDateChooser fechafinal;
    private com.toedter.calendar.JDateChooser fechainicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound3;
    private Modelo.JpanelRound jpanelRound4;
    private javax.swing.JLabel lbl;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JTextField txtidSalida;
    private javax.swing.JTextField txtnumSalida;
    // End of variables declaration//GEN-END:variables
}
