/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoUsuario;

import Modelo.usuarios;


import java.awt.Color;


/**
 *
 * @author Adrian
 */
public class loginn extends javax.swing.JPanel {
DaoUsuario daoU = new DaoUsuario();
    usuarios us = new usuarios();
   pantallaPrincipal pP;
    public loginn(pantallaPrincipal pP) {
        
        initComponents();
        this.pP = pP;
        lblregistrarse.setText("<html><u>Registrate!</u></html>");
    }

    public loginn() {
        initComponents();
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcontrase = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        lblregistrarse = new javax.swing.JLabel();

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setPreferredSize(new java.awt.Dimension(982, 740));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("Inicia sesion");
        jpanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Correo electronico");
        jpanelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtcorreo.setText("alguien@example.com");
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jpanelRound1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 310, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 255));
        jLabel9.setText("Contraseña");
        jpanelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        txtcontrase.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcontrase.setForeground(new java.awt.Color(204, 204, 204));
        txtcontrase.setText("********");
        txtcontrase.setOpaque(true);
        txtcontrase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontraseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraseFocusLost(evt);
            }
        });
        txtcontrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcontraseMousePressed(evt);
            }
        });
        jpanelRound1.add(txtcontrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 310, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 204, 255));
        jLabel10.setText("¿No tienes cuenta?");
        jpanelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 204, 255));
        jLabel11.setText("ECUMARKET");
        jpanelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        btnentrar.setBackground(new java.awt.Color(0, 153, 255));
        btnentrar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Iniciar sesion");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 200, -1));

        rSLabelBorderRound1.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelBorderRound1.setForeground(new java.awt.Color(255, 0, 0));
        rSLabelBorderRound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lalaa.png"))); // NOI18N
        rSLabelBorderRound1.setText("Ecumarket");
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(255, 255, 255));
        jpanelRound1.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 250, 230));

        lblregistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistrarse.setText("Registrate!");
        lblregistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblregistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblregistrarseMouseExited(evt);
            }
        });
        jpanelRound1.add(lblregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 543, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusGained
           if (txtcorreo.getText().equals("alguien@example.com")) {
            txtcorreo.setText("");
            txtcorreo.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtcorreoFocusGained

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
      if (txtcorreo.getText().equals("")) {
            txtcorreo.setText("alguien@example.com");
            txtcorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
          if(String.valueOf(txtcontrase.getPassword()).isEmpty()){
        txtcontrase.setText("********");
txtcontrase.setForeground(Color.gray);
}
if(txtcorreo.getText().equals("alguien@example.com")){
txtcorreo.setText("");
txtcorreo.setForeground(Color.blue);}
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcontraseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseFocusGained
         if (String.valueOf(txtcontrase.getPassword()).equals("********")) {
            txtcontrase.setText("");
            txtcontrase.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtcontraseFocusGained

    private void txtcontraseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseFocusLost
   if (String.valueOf(txtcontrase.getPassword()).isEmpty()) {
            txtcontrase.setText("**************");
            txtcontrase.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcontraseFocusLost

    private void txtcontraseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseMousePressed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
  us = daoU.login(txtcorreo.getText(), txtcontrase.getText());
if(us.getIdusuario() != 0){          
            
    pantallaPrincipal m = new pantallaPrincipal(us);
   Inicio h=new Inicio();
        h.setSize(982,740);
        h.setLocation(0,0);
        
        
    // Mostrar toast de bienvenida
    Utilidades.mostrarToast(m, "¡Bienvenido, " + us.getTipoUsuario().toUpperCase() + "!");

    String tipo = us.getTipoUsuario();
    switch(tipo){
        case "Vendedor" -> {
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(false);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(false);
            pantallaPrincipal.btnProveedor.setEnabled(false);
            pantallaPrincipal.btnProductos.setEnabled(false);
           }
        case "Almacenero" -> {
            pantallaPrincipal.btnSalidas.setEnabled(false);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(false);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);
           }
        case "Administrador" -> {
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);
           }
        default -> Utilidades.mostrarToast(m, "⚠ Usuario sin rol válido.");
    }

    pantallaPrincipal.txtiduser.setText(us.getIdusuario() + "");
    pantallaPrincipal.txtuser.setText(us.getUsuario());
    m.setVisible(true);
    
    dispose();
} else {
    Utilidades.mostrarToast(null, "❌ Acceso denegado");
}
        
        
    
        
        
        
        
        
     /*    us = daoU.login(txtcorreo.getText(), txtcontrase.getText());
if(us.getIdusuario() != 0){
    pantallaPrincipal m = new pantallaPrincipal();
    Utilidades.mostrarToast(m, "¡Bienvenido, " + us.getTipoUsuario().toUpperCase() + "!");
pantallaPrincipal.txtiduser.setText(us.getIdusuario() + "");
pantallaPrincipal.txtuser.setText(us.getUsuario());
m.setVisible(true);
dispose();
   
    String tipo = us.getTipoUsuario();
    switch(tipo){
        case "Vendedor" -> {
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(false);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(false);
            pantallaPrincipal.btnProveedor.setEnabled(false);
            pantallaPrincipal.btnProductos.setEnabled(false);
        }
        case "Almacenero" -> {
            pantallaPrincipal.btnSalidas.setEnabled(false);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(false);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);
        }
        case "Administrador" -> {
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);

          
        }
        default -> Utilidades.mostrarToast(m, "⚠ Usuario sin rol válido.");
    }
  
    pantallaPrincipal.txtiduser.setText(us.getIdusuario() + "");
    pantallaPrincipal.iconusuario.setText(us.getUsuario());

    //m.setVisible(true);
    dispose();
} else {
    Utilidades.mostrarToast(null, "❌ Acceso denegado");
}*/
    }//GEN-LAST:event_btnentrarActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void lblregistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarseMouseClicked
        pP.mostrarRegistro();
    }//GEN-LAST:event_lblregistrarseMouseClicked

    private void lblregistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarseMouseEntered
        lblregistrarse.setForeground(Color.black);
    }//GEN-LAST:event_lblregistrarseMouseEntered

    private void lblregistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarseMouseExited
        lblregistrarse.setForeground(Color.gray);
    }//GEN-LAST:event_lblregistrarseMouseExited
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private Modelo.JpanelRound jpanelRound1;
    private javax.swing.JLabel lblregistrarse;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private javax.swing.JPasswordField txtcontrase;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
