/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import javax.swing.JOptionPane;
import Dao.DaoUsuario;
import Modelo.usuarios;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;

/**
 *
 * @author Adrian
 */
public class Login extends javax.swing.JFrame {
DaoUsuario daoU = new DaoUsuario();
    usuarios us = new usuarios();
    
   pantallaPrincipal pP;
    public Login(pantallaPrincipal pP) {
        

        initComponents();
        this.pP = pP;
        
        
    }
    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnentrar);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcontrase = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        btnVerPassword = new javax.swing.JCheckBox();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(970, 587));
        setPreferredSize(new java.awt.Dimension(970, 587));
        getContentPane().setLayout(new java.awt.CardLayout());

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setPreferredSize(new java.awt.Dimension(982, 740));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("Inicia sesión");
        jpanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Correo electrónico ");
        jpanelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtcorreo.setText("alguien@example.com");
        txtcorreo.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });
        jpanelRound1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 310, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 255));
        jLabel9.setText("Contraseña");
        jpanelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        txtcontrase.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtcontrase.setForeground(new java.awt.Color(204, 204, 204));
        txtcontrase.setText("++++++");
        txtcontrase.setOpaque(true);
        txtcontrase.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtcontrase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontraseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraseFocusLost(evt);
            }
        });
        txtcontrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcontraseMousePressed(evt);
            }
        });
        jpanelRound1.add(txtcontrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 310, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¿No tienes cuenta?");
        jpanelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, 20));

        btnentrar.setBackground(new java.awt.Color(0, 153, 255));
        btnentrar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Inicia sesión");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 200, -1));

        btnVerPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerPassword.setForeground(new java.awt.Color(102, 204, 255));
        btnVerPassword.setText("Ver Contraseña");
        btnVerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPasswordActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 140, -1));

        btnSalir.setBackground(new java.awt.Color(0, 153, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, -1));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelBorderRound1.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelBorderRound1.setForeground(new java.awt.Color(255, 0, 0));
        rSLabelBorderRound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/logoo.png"))); // NOI18N
        rSLabelBorderRound1.setText("Ecumarket");
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(102, 204, 255));
        jPanel1.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 230));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ECUMARKET");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jpanelRound1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 360, 590));

        getContentPane().add(jpanelRound1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusGained
        if (txtcorreo.getText().equals("alguien@example.com")) {
            txtcorreo.setText("");
            txtcorreo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcorreoFocusGained

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
        if (String.valueOf(txtcorreo.getText()).isEmpty()) {
            txtcorreo.setText("alguien@example.com");
            txtcorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        if(String.valueOf(txtcontrase.getPassword()).isEmpty()){
            txtcontrase.setText("++++++");
            txtcontrase.setForeground(Color.gray);
        }
        if(txtcorreo.getText().equals("alguien@example.com")){
            txtcorreo.setText("");
            txtcorreo.setForeground(Color.black);}
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtcontraseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseFocusGained
        if (String.valueOf(txtcontrase.getPassword()).equals("++++++")) {
            txtcontrase.setText("");
            txtcontrase.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcontraseFocusGained

    private void txtcontraseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseFocusLost
        if (String.valueOf(txtcontrase.getPassword()).isEmpty()) {
            txtcontrase.setText("++++++");
            txtcontrase.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcontraseFocusLost

    private void txtcontraseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseMousePressed
       if (String.valueOf(txtcontrase.getPassword()).equals("++++++")) {
        txtcontrase.setText("");
        txtcontrase.setForeground(Color.black);
    }
    }//GEN-LAST:event_txtcontraseMousePressed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        us = daoU.login(txtcorreo.getText(), txtcontrase.getText());
if (us.getIdusuario() != 0) {
    pantallaPrincipal m = new pantallaPrincipal(us);
    this.dispose();
   // Inicio h = new Inicio();
   /// h.setSize(982, 740);
   // h.setLocation(0, 0);

    
    Utilidades.mostrarToast(m, "¡Bienvenido, " + us.getTipoUsuario().toUpperCase() + "!");

    String tipo = us.getTipoUsuario();

    switch (tipo) {
        case "Vendedor":
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(false);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(false);
            pantallaPrincipal.btnProveedor.setEnabled(false);
            pantallaPrincipal.btnProductos.setEnabled(false);
            break;

        case "Almacenero":
            pantallaPrincipal.btnSalidas.setEnabled(false);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(false);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);
            break;

        case "Administrador":
            pantallaPrincipal.btnSalidas.setEnabled(true);
            pantallaPrincipal.btnCategorias.setEnabled(true);
            pantallaPrincipal.btnClientes.setEnabled(true);
            pantallaPrincipal.btnEntradas.setEnabled(true);
            pantallaPrincipal.btnProveedor.setEnabled(true);
            pantallaPrincipal.btnProductos.setEnabled(true);
            pantallaPrincipal.btnRegistro.setVisible(true);
            break;

        default:
            Utilidades.mostrarToast(m, "⚠ Usuario sin rol válido.");
            break;
    }

    pantallaPrincipal.txtiduser.setText(us.getIdusuario() + "");
    m.setVisible(true);
} else {
    Utilidades.mostrarToast(this, "❌ Acceso denegado. Verifica tus datos.");
}
    }//GEN-LAST:event_btnentrarActionPerformed

    private void btnVerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPasswordActionPerformed
       String pass = String.valueOf(txtcontrase.getPassword());

    // Si el texto es el placeholder, no hacemos nada
    if (pass.equals("++++++")) {
        btnVerPassword.setSelected(false); // Opcional: desmarcar
        return;
    }

    if (btnVerPassword.isSelected()) {
        txtcontrase.setEchoChar((char) 0); // Mostrar caracteres reales
    } else {
        txtcontrase.setEchoChar('•'); // O '*'
    }
    }//GEN-LAST:event_btnVerPasswordActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que quieres cerrar la aplicación?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtcorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyPressed
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
    txtcontrase.requestFocusInWindow();
}
    }//GEN-LAST:event_txtcorreoKeyPressed

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        
        
    }//GEN-LAST:event_txtcorreoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      try {
            FlatMacLightLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox btnVerPassword;
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private Modelo.JpanelRound jpanelRound1;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private javax.swing.JPasswordField txtcontrase;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
