/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import Formularios.Utilidades;
import Formularios.loginn;
import Modelo.usuarios;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Adrian
 */
public final class pantallaPrincipal extends javax.swing.JFrame {
private usuarios us;

   
    public pantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        bloquearComponentes();
        mostrarLogin(); 
      
        
    }

    public pantallaPrincipal(usuarios usuarioLogueado) {
        initComponents();
        setLocationRelativeTo(null);
        this.us = usuarioLogueado; 
       configurarPorRol();
       activarComponentes();
        txtiduser.setText(String.valueOf(us.getIdusuario())); 
        txtuser.setText(us.getUsuario());
        Utilidades.mostrarToast(this, "¡Bienvenido, " + us.getTipoUsuario().toUpperCase() + "!"); // Muestra un mensaje de bienvenida
        
        getContentPane().add(contenedor);
    }

   public JPanel getContenedor() {
        return contenedor;
    }
    public void mostrarLogin() {
        loginn L = new loginn(this); 
        L.setSize(1270, 790);
        L.setLocation(0, 0); 
        contenedor.removeAll(); 
        contenedor.add(L, BorderLayout.CENTER); 
        contenedor.revalidate(); 
       contenedor.repaint(); 
      // L.setVisible(true);
    //L.setBounds(0, 0, this.getWidth(), this.getHeight());
    //L.setBackground(Color.decode("#00BFFF"));
    }

  
    public void mostrarRegistro() {
        Registro R = new Registro(this); 
        R.setSize(1270, 790); 
        R.setLocation(0, 0); 
        contenedor.removeAll();
        contenedor.add(R, BorderLayout.CENTER); 
        contenedor.revalidate();
        contenedor.repaint(); 
    }

    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbotones = new Modelo.JpanelRound();
        btnInicio = new RSMaterialComponent.RSButtonMaterialIconShadow();
        btnCategorias = new RSMaterialComponent.RSButtonMaterialIconShadow();
        btnClientes = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProveedor = new RSMaterialComponent.RSButtonMaterialIconShadow();
        btnEntradas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProductos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalidas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalida = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtiduser = new javax.swing.JLabel();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        txtuser = new RSMaterialComponent.RSLabelTextIcon();
        btnCerrarSesionn = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnLogin = new RSMaterialComponent.RSButtonMaterialIconDos();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecumarket");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        panelbotones.setBackground(new java.awt.Color(204, 0, 204));
        panelbotones.setRoundBottomLeft(50);
        panelbotones.setRoundBottomRight(50);
        panelbotones.setRoundTopLeft(50);
        panelbotones.setRoundTopRight(50);
        panelbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(51, 204, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBackgroundHover(new java.awt.Color(153, 204, 0));
        btnInicio.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnInicio.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelbotones.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        btnCategorias.setBackground(new java.awt.Color(51, 204, 255));
        btnCategorias.setText("Categorias");
        btnCategorias.setBackgroundHover(new java.awt.Color(51, 255, 51));
        btnCategorias.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnCategorias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOOP);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        panelbotones.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, -1));

        btnClientes.setBackground(new java.awt.Color(51, 204, 255));
        btnClientes.setText("Clientes");
        btnClientes.setBackgroundHover(new java.awt.Color(204, 255, 204));
        btnClientes.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LANGUAGE);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelbotones.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        btnProveedor.setBackground(new java.awt.Color(51, 204, 255));
        btnProveedor.setText("Proveedor");
        btnProveedor.setBackgroundHover(new java.awt.Color(102, 255, 102));
        btnProveedor.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORAGE);
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        panelbotones.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, -1));

        btnEntradas.setBackground(new java.awt.Color(0, 204, 255));
        btnEntradas.setText("Entrada De Productos");
        btnEntradas.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REDO);
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });
        panelbotones.add(btnEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, -1));

        btnProductos.setBackground(new java.awt.Color(0, 204, 255));
        btnProductos.setText("Productos");
        btnProductos.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REDO);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panelbotones.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, -1));

        btnSalidas.setBackground(new java.awt.Color(0, 204, 255));
        btnSalidas.setText("Gestion De Pedidos");
        btnSalidas.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HISTORY);
        btnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidasActionPerformed(evt);
            }
        });
        panelbotones.add(btnSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 210, -1));

        btnSalida.setBackground(new java.awt.Color(0, 204, 255));
        btnSalida.setText("Pedidos");
        btnSalida.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERM_CONTACT_CALENDAR);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        panelbotones.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 210, -1));

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setText("Salir");
        btnSalir.setBackgroundHover(new java.awt.Color(204, 204, 0));
        btnSalir.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SD_CARD);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelbotones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 120, -1));

        txtiduser.setText("1");
        panelbotones.add(txtiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, -1));

        rSLabelBorderRound1.setBackground(new java.awt.Color(0, 153, 255));
        rSLabelBorderRound1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelBorderRound1.setText("Ecumarket");
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(0, 204, 255));
        rSLabelBorderRound1.setFont(new java.awt.Font("Roboto Bold", 3, 18)); // NOI18N
        panelbotones.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 103, -1));

        txtuser.setForeground(new java.awt.Color(204, 255, 102));
        txtuser.setColorIcon(new java.awt.Color(255, 255, 255));
        panelbotones.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        btnCerrarSesionn.setBackground(new java.awt.Color(0, 204, 255));
        btnCerrarSesionn.setText("Cerrar Sesion");
        btnCerrarSesionn.setBackgroundHover(new java.awt.Color(204, 204, 0));
        btnCerrarSesionn.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnCerrarSesionn.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SD_CARD);
        btnCerrarSesionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionnActionPerformed(evt);
            }
        });
        panelbotones.add(btnCerrarSesionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 210, -1));

        btnLogin.setBackground(new java.awt.Color(0, 204, 255));
        btnLogin.setText("Login");
        btnLogin.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SPA);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelbotones.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelbotones, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        btnInicio.setSelected(false);
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(true);
        btnSalida.setSelected(false);
        btnCerrarSesionn.setSelected(false);
       
     
int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que quieres cerrar la aplicación?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        btnInicio.setSelected(false);      
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(true);
        Salidas Sal=new Salidas();
        Sal.setSize(1270, 790);
        Sal.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(Sal,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidasActionPerformed
         btnInicio.setSelected(false);        
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(true);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        ListaSalidas LS=new ListaSalidas();
        LS.setSize(982,740);
        LS.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(LS,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnSalidasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
      btnInicio.setSelected(false);      
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(true);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        
        
        Producto PR = new Producto();
        PR.setSize(982,740);
        PR.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(PR,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        btnInicio.setSelected(false);       
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(true);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        Entradas En=new Entradas();
        En.setSize(982,740);
        En.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(En,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        btnInicio.setSelected(false);
        btnCategorias.setSelected(false);       
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(true);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        Provedores P=new Provedores();
        P.setSize(1270, 790);
        P.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(P,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        btnInicio.setSelected(false);
        btnCategorias.setSelected(false);
        btnClientes.setSelected(true);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        Clientes CL=new Clientes();
        CL.setSize(1270, 790);
        CL.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(CL,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
          btnInicio.setSelected(false);     
        btnCategorias.setSelected(true);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        Categorias C=new Categorias();
        C.setSize(1270, 790);
        C.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(C,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        btnInicio.setSelected(true);
        btnCategorias.setSelected(false);
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalir.setSelected(false);
        btnSalida.setSelected(false);
        Inicio i=new Inicio();
        i.setSize(1270, 790);
        i.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(i,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCerrarSesionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionnActionPerformed
btnCerrarSesionn.setSelected(true);
btnInicio.setSelected(false);
btnCategorias.setSelected(false);
btnClientes.setSelected(false);
btnEntradas.setSelected(false);
btnProveedor.setSelected(false);
btnSalidas.setSelected(false);
btnProductos.setSelected(false);
btnSalir.setSelected(false);
btnSalida.setSelected(false);
btnCerrarSesionn.setSelected(false); 

   cerrarSesion();

 /*loginn m=new loginn();
        m.setVisible(true);
        dispose();
       pantallaPrincipal.txtiduser.setText("");    
 pantallaPrincipal.txtuser.setText("");
    loginn ll = new loginn();
    ll.setSize(982, 740);     
    ll.setVisible(true);*/
    // JOptionPane.showMessageDialog(null, "Sesión cerrada correctamente", "Cerrar sesión", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCerrarSesionnActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         
btnInicio.setSelected(false);
btnCategorias.setSelected(false);
btnClientes.setSelected(false);
btnEntradas.setSelected(false);
btnProveedor.setSelected(false);
btnSalidas.setSelected(false);
btnProductos.setSelected(false);
btnSalir.setSelected(false);
btnSalida.setSelected(false);
btnCerrarSesionn.setSelected(false); 
btnLogin.setSelected(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

private void configurarPorRol() {
        String tipo = us.getTipoUsuario();
        switch (tipo) {
            case "Vendedor" -> {
                // Configuración para Vendedor
                pantallaPrincipal.btnSalidas.setEnabled(true);
                pantallaPrincipal.btnCategorias.setEnabled(false);
                pantallaPrincipal.btnClientes.setEnabled(true);
                pantallaPrincipal.btnEntradas.setEnabled(false);
                pantallaPrincipal.btnProveedor.setEnabled(false);
                pantallaPrincipal.btnProductos.setEnabled(false);
                  pantallaPrincipal.btnSalir.setEnabled(true);
            }
            case "Almacenero" -> {
                // Configuración para Almacenero
                pantallaPrincipal.btnSalidas.setEnabled(false);
                pantallaPrincipal.btnCategorias.setEnabled(true);
                pantallaPrincipal.btnClientes.setEnabled(false);
                pantallaPrincipal.btnEntradas.setEnabled(true);
                pantallaPrincipal.btnProveedor.setEnabled(true);
                pantallaPrincipal.btnProductos.setEnabled(true);
                  pantallaPrincipal.btnSalir.setEnabled(true);
            }
            case "Administrador" -> {
                // Configuración para Administrador
                pantallaPrincipal.btnSalidas.setEnabled(true);
                pantallaPrincipal.btnCategorias.setEnabled(true);
                pantallaPrincipal.btnClientes.setEnabled(true);
                pantallaPrincipal.btnEntradas.setEnabled(true);
                pantallaPrincipal.btnProveedor.setEnabled(true);
                pantallaPrincipal.btnProductos.setEnabled(true);
                pantallaPrincipal.btnSalir.setEnabled(true);
            }
            default -> Utilidades.mostrarToast(this, "⚠ Usuario sin rol válido.");
        }
    }

private void bloquearComponentes() {
    btnInicio.setEnabled(false);
    btnCategorias.setEnabled(false);
    btnClientes.setEnabled(false);
    btnEntradas.setEnabled(false);
    btnProveedor.setEnabled(false);
    btnSalidas.setEnabled(false);
    btnProductos.setEnabled(false);
    btnCerrarSesionn.setEnabled(false);
    btnSalida.setEnabled(false);
    btnSalir.setEnabled(true);
    btnLogin.setEnabled(false);
}
private void activarComponentes() {
    btnInicio.setEnabled(true);
    btnCategorias.setEnabled(true);
    btnClientes.setEnabled(true);
    btnEntradas.setEnabled(true);
    btnProveedor.setEnabled(true);
    btnSalidas.setEnabled(true);
    btnProductos.setEnabled(true);
    btnCerrarSesionn.setEnabled(true);
    btnSalida.setEnabled(true);
    btnSalir.setEnabled(true);  
    //panelbotones.setVisible(true);
    btnLogin.setEnabled(true);
}
public void cerrarSesion() {
    txtiduser.setText(""); 
    txtiduser.setText(""); 

    
     Login m=new Login();
        m.setVisible(true);
        dispose();

    
    pantallaPrincipal.txtiduser.setText("");  
    pantallaPrincipal.txtuser.setText("");   
    
    JOptionPane.showMessageDialog(null, "Sesión cerrada correctamente", "Cerrar sesión", JOptionPane.INFORMATION_MESSAGE);

   
    dispose(); 
}
/*private void bloquearComponentes() {
    
     //panelbotones.setVisible(false);
    btnInicio.setVisible(false);
    btnCategorias.setVisible(false);
    btnClientes.setVisible(false);
    btnEntradas.setVisible(false);
    btnProveedor.setVisible(false);
    btnSalidas.setVisible(false);
    btnProductos.setVisible(false);
    btnCerrarSesionn.setVisible(false);
    btnSalida.setVisible(false);
    btnSalir.setVisible(true);
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnCategorias;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnCerrarSesionn;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnClientes;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnEntradas;
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnInicio;
    private RSMaterialComponent.RSButtonMaterialIconDos btnLogin;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnProductos;
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnProveedor;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnSalida;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnSalidas;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    private javax.swing.JPanel contenedor;
    public static Modelo.JpanelRound panelbotones;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    public static javax.swing.JLabel txtiduser;
    public static RSMaterialComponent.RSLabelTextIcon txtuser;
    // End of variables declaration//GEN-END:variables

 

        
    

    
}
