/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 *
 * @author Adrian
 */
public class pantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form pantallaPrincipal
     */
    public pantallaPrincipal() {
        initComponents();     
       JPanel panelCentral = new JPanel();
panelCentral.setLayout(new BorderLayout());

JPanel panelBotones = new JPanel(); // por ejemplo arriba
JPanel panlSecu = new JPanel(); // el contenedor de formularios
panlSecu.setLayout(new BorderLayout()); // muy importante

panelCentral.add(panelBotones, BorderLayout.NORTH); // o WEST si es lateral
panelCentral.add(panlSecu, BorderLayout.CENTER);

this.add(panelCentral); // añades todo al JFrame

        
        setLocationRelativeTo(null);
        //contenedor.setBorder(new BordeRedondeado(50));
       // contenedorbotones.setBorder(new BordeRedondeado(80));
        loginn L=new loginn();
        L.setSize(982,740);
        L.setLocation(0,0);
          contenedor.removeAll();
        contenedor.add(L,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanlSecu = new Modelo.JpanelRound();
        contenedor = new Modelo.JpanelRound();
        jpanelRound2 = new Modelo.JpanelRound();
        btnInicio = new RSMaterialComponent.RSButtonMaterialIconShadow();
        btnCategorias = new RSMaterialComponent.RSButtonMaterialIconShadow();
        btnClientes = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProveedor = new RSMaterialComponent.RSButtonMaterialIconShadow();
        l = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEntradas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProductos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalidas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalida = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtiduser = new javax.swing.JLabel();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        txtuser = new RSMaterialComponent.RSLabelTextIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecumarket");
        setBackground(new java.awt.Color(255, 255, 255));

        PanlSecu.setBackground(new java.awt.Color(255, 255, 255));
        PanlSecu.setPreferredSize(new java.awt.Dimension(1261, 787));
        PanlSecu.setRoundBottomLeft(40);
        PanlSecu.setRoundBottomRight(40);
        PanlSecu.setRoundTopLeft(40);
        PanlSecu.setRoundTopRight(40);
        PanlSecu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(1007, 775));
        contenedor.setRoundBottomLeft(30);
        contenedor.setRoundBottomRight(30);
        contenedor.setRoundTopLeft(30);
        contenedor.setRoundTopRight(30);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        PanlSecu.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 770));

        jpanelRound2.setBackground(new java.awt.Color(204, 0, 204));
        jpanelRound2.setRoundBottomLeft(50);
        jpanelRound2.setRoundBottomRight(50);
        jpanelRound2.setRoundTopLeft(50);
        jpanelRound2.setRoundTopRight(50);
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(51, 204, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBackgroundHover(new java.awt.Color(153, 204, 0));
        btnInicio.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnInicio.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        btnCategorias.setBackground(new java.awt.Color(51, 204, 255));
        btnCategorias.setText("Categorias");
        btnCategorias.setBackgroundHover(new java.awt.Color(51, 255, 51));
        btnCategorias.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnCategorias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOOP);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, -1));

        btnClientes.setBackground(new java.awt.Color(51, 204, 255));
        btnClientes.setText("Clientes");
        btnClientes.setBackgroundHover(new java.awt.Color(204, 255, 204));
        btnClientes.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LANGUAGE);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        btnProveedor.setBackground(new java.awt.Color(51, 204, 255));
        btnProveedor.setText("Proveedor");
        btnProveedor.setBackgroundHover(new java.awt.Color(102, 255, 102));
        btnProveedor.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORAGE);
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, -1));

        l.setBackground(new java.awt.Color(51, 204, 255));
        l.setText("Usuario");
        l.setBackgroundHover(new java.awt.Color(102, 255, 102));
        l.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        l.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });
        jpanelRound2.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, -1));

        btnEntradas.setBackground(new java.awt.Color(0, 204, 255));
        btnEntradas.setText("Entrada De Productos");
        btnEntradas.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REDO);
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, -1));

        btnProductos.setBackground(new java.awt.Color(0, 204, 255));
        btnProductos.setText("Productos");
        btnProductos.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REDO);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, -1));

        btnSalidas.setBackground(new java.awt.Color(0, 204, 255));
        btnSalidas.setText("Gestion De Pedidos");
        btnSalidas.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HISTORY);
        btnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 210, -1));

        btnSalida.setBackground(new java.awt.Color(0, 204, 255));
        btnSalida.setText("Pedidos");
        btnSalida.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalida.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERM_CONTACT_CALENDAR);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 210, -1));

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SD_CARD);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 110, -1));

        txtiduser.setText("1");
        jpanelRound2.add(txtiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, -1));

        rSLabelBorderRound1.setBackground(new java.awt.Color(0, 153, 255));
        rSLabelBorderRound1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelBorderRound1.setText("Ecumarket");
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(0, 204, 255));
        rSLabelBorderRound1.setFont(new java.awt.Font("Roboto Bold", 3, 18)); // NOI18N
        jpanelRound2.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 103, -1));

        txtuser.setForeground(new java.awt.Color(204, 255, 102));
        txtuser.setColorIcon(new java.awt.Color(255, 255, 255));
        jpanelRound2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        PanlSecu.add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 250, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanlSecu, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanlSecu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        btnInicio.setSelected(true);
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
    //  btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnSalida.setSelected(false);
        btnProductos.setSelected(false);
        Inicio i=new Inicio();
        i.setSize(982,740);
        i.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(i,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
       /* btnCategorias.setSelected(true);
        btnInicio.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        // btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalida.setSelected(false);
        Categorias C=new Categorias();
        C.setSize(982,740);
        C.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(C,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();*/
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        btnCategorias.setSelected(false);
        btnClientes.setSelected(true);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        //  btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalida.setSelected(false);
        Clientes CL=new Clientes();
        CL.setSize(982,740);
        CL.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(CL,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
       
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(true);
        btnProveedor.setSelected(false);
        // btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalida.setSelected(false);
        Entradas En=new Entradas();
        En.setSize(982,740);
        En.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(En,BorderLayout.CENTER);
        contenedor.revalidate();
       contenedor.repaint();
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
      /*  btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        // btnUsuarios.setSelected(false);
        btnProductos.setSelected(true);
        btnSalida.setSelected(false);
        Producto PR=new Producto();
        PR.setSize(982,740);
        PR.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(PR,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();*/
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidasActionPerformed
        btnCategorias.setSelected(false);

        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        // btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnSalida.setSelected(true);
        btnProductos.setSelected(false);
        ListaSalidas LS=new ListaSalidas();
        LS.setSize(982,740);
        LS.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(LS,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnSalidasActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(true);
        //btnUsuarios.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        btnSalida.setSelected(false);
        Provedores P=new Provedores();
        P.setSize(1007, 775);
        P.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(P,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
     /*   btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        // btnUsuarios.setSelected(false);
        btnSalidas.setSelected(true);
        btnSalida.setSelected(false);
        Salidas Sal=new Salidas();
        Sal.setSize(982,740);
        Sal.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(Sal,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();*/
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       btnCategorias.setSelected(false);
        btnCategorias.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        //btnUsuarios.setSelected(true);
        btnSalida.setSelected(false);
        loginn L=new loginn();
        L.setSize(982,740);
        L.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(L,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
        
        /* loginn ll=new loginn();
        ll.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
       /* btnCategorias.setSelected(false);
        btnInicio.setSelected(false);
        btnClientes.setSelected(false);
        btnEntradas.setSelected(false);
        btnProveedor.setSelected(false);
        btnSalidas.setSelected(false);
        btnProductos.setSelected(false);
        // btnUsuarios.setSelected(true);
        btnSalida.setSelected(false);
        Usuarios c=new Usuarios();
        c.setSize(982,740);
        c.setLocation(0,0);

        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();*/
    }//GEN-LAST:event_lActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Modelo.JpanelRound PanlSecu;
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnCategorias;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnClientes;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnEntradas;
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnInicio;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnProductos;
    public static RSMaterialComponent.RSButtonMaterialIconShadow btnProveedor;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnSalida;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnSalidas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    private Modelo.JpanelRound contenedor;
    private Modelo.JpanelRound jpanelRound2;
    public static RSMaterialComponent.RSButtonMaterialIconDos l;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    public static javax.swing.JLabel txtiduser;
    public static RSMaterialComponent.RSLabelTextIcon txtuser;
    // End of variables declaration//GEN-END:variables

    static class LULU {

        
    }
}
