/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoCategoria;
import Dao.DaoProductos;
import Modelo.Categoria;
import Modelo.productos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tadeo
 */
public class Producto extends javax.swing.JPanel {
productos p=new productos();
    DaoProductos daoP=new DaoProductos();
    DefaultTableModel modelo=new DefaultTableModel();

    Categoria ct=new Categoria();
    DaoCategoria daoCt=new DaoCategoria();
    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
      listarProductos();
     //   numProducto();
    }

    private void listarProductos(){
        List<productos> lista=daoP.Listar();
        modelo=(DefaultTableModel) tablaProductos.getModel();
        Object[] ob=new Object[5];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdproducto();
            ob[1]=lista.get(i).getNomProd();
            ob[2]=lista.get(i).getStock();
            ob[3]=lista.get(i).getIdCategoria();
            ob[4]=lista.get(i).getPrecioV();
            modelo.addRow(ob);
        }
       tablaProductos.setModel(modelo);
    }

    void numProducto(){
        int numero=daoP.numProducto();
        if(numero==0){
        txtid.setText("1");
        }else{
        int i=numero;
        i=i+1;
        txtid.setText(i+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jpanelRound2 = new Modelo.JpanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidCategoria = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtNomCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btnBuscarIdCategiria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttprecio = new javax.swing.JTextField();
        btnGuradar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnElimar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jpanelRound3 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound1.setPreferredSize(new java.awt.Dimension(982, 740));

        jpanelRound2.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 12))); // NOI18N
        jpanelRound2.setRoundBottomLeft(25);
        jpanelRound2.setRoundBottomRight(25);
        jpanelRound2.setRoundTopLeft(25);
        jpanelRound2.setRoundTopRight(25);

        jLabel3.setText("Nombre");

        jLabel6.setText("Id categoria");

        jLabel8.setText("Precio. V");

        jLabel2.setText("ID");

        btnBuscarIdCategiria.setText("Buscar");
        btnBuscarIdCategiria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdCategiriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Stock");

        jLabel7.setText("Categoria");

        btnGuradar.setText("Regisrar");
        btnGuradar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuradarActionPerformed(evt);
            }
        });

        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnElimar.setText("Eliminar");
        btnElimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addComponent(txtidCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscarIdCategiria))
                    .addComponent(jLabel7)
                    .addComponent(txtNomCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txttprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addComponent(btnElimar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addComponent(btnGuradar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdCategiria))
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(txtNomCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(txttprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuradar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElimar)
                    .addComponent(btnBuscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanelRound3.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 12))); // NOI18N
        jpanelRound3.setRoundBottomLeft(25);
        jpanelRound3.setRoundBottomRight(25);
        jpanelRound3.setRoundTopLeft(25);
        jpanelRound3.setRoundTopRight(25);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stocok", "IdCat", "Precio V"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpanelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
   int fila=tablaProductos.getSelectedRow();
        txtid.setText(tablaProductos.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaProductos.getValueAt(fila, 1).toString());
        txtstock.setText(tablaProductos.getValueAt(fila, 2).toString());
        txtidCategoria.setText(tablaProductos.getValueAt(fila, 3).toString());
        txttprecio.setText(tablaProductos.getValueAt(fila, 4).toString());

        ct.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
        if(daoCt.buscar(ct)){
            txtNomCategoria.setText(ct.getNomCategoria());
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnGuradarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuradarActionPerformed
        p.setIdproducto(Integer.parseInt(txtid.getText()));
        p.setNomProd(txtnombre.getText());
       p.setStock(Integer.parseInt(txtstock.getText()));
        p.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
        p.setPrecioV(Double.parseDouble(txttprecio.getText()));
        if(daoP.insertar(p)){
           
            JOptionPane.showMessageDialog(null,"Producto Registrado Con Exito");
            limpiarTablaProductos();
            listarProductos();
            numProducto();
        }else{
        JOptionPane.showMessageDialog(null, "No se pudo registrar el Producto");   
        }
    }//GEN-LAST:event_btnGuradarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         int fila=tablaProductos.getSelectedRow();
        if(fila==-1&&txtid.getText().isEmpty()){
           
          JOptionPane.showMessageDialog(null,"Seleccione un Proveedor");
        }else{
            p.setIdproducto(Integer.parseInt(txtid.getText()));
            p.setNomProd(txtnombre.getText());
             p.setStock(Integer.parseInt(txtstock.getText()));
            p.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
            p.setPrecioV(Double.parseDouble(txttprecio.getText()));
            if(daoP.editar(p)){
             
                limpiarCampos();
                limpiarTablaProductos();
                listarProductos();
            }else{
              JOptionPane.showMessageDialog(null,"Se edito con exito");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnElimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimarActionPerformed
       if(!txtid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar el Producto?","Confirmar",2);
            if(confirmacion==0){
                p.setIdproducto(Integer.parseInt(txtid.getText()));
                daoP.eliminar(p);
                limpiarCampos();
                limpiarTablaProductos();
                listarProductos();
            
            }
        }else{
          JOptionPane.showMessageDialog(null,"Se elimino con exito");
        }        
    }//GEN-LAST:event_btnElimarActionPerformed

    private void btnBuscarIdCategiriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdCategiriaActionPerformed
        BuscarDato.tipo=true;
        BuscarDato.entrada=false;
        BuscarDato m=new BuscarDato();
        m.setVisible(true);
    }//GEN-LAST:event_btnBuscarIdCategiriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       p.setIdproducto(Integer.parseInt(txtid.getText()));
        if(daoP.buscar(p)){
            txtid.setText(p.getIdproducto()+"");
            txtnombre.setText(p.getNomProd());
            txtidCategoria.setText(p.getIdCategoria()+"");
            txttprecio.setText(p.getPrecioV()+"");
            txtstock.setText(p.getStock()+"");
            ct.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
            if(daoCt.buscar(ct)){
                txtNomCategoria.setText(ct.getNomCategoria());
            }
        }else{
           JOptionPane.showMessageDialog(null,"El Producto No Existe");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

private void limpiarTablaProductos() {
       for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }

    private void limpiarCampos() {
 txtid.setText("");
txtnombre.setText("");
txtstock.setText("");
txtNomCategoria.setText("");
txttprecio.setText("");
txtidCategoria.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarIdCategiria;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnElimar;
    private javax.swing.JButton btnGuradar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound3;
    private javax.swing.JTable tablaProductos;
    public static javax.swing.JTextField txtNomCategoria;
    private javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtidCategoria;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttprecio;
    // End of variables declaration//GEN-END:variables
}
