/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoCategoria;
import Dao.DaoProductos;
import Dao.conexion;
import Formularios.BuscarDato;
import Modelo.Categoria;
import Modelo.productos;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Tadeo
 */
public final class Producto extends javax.swing.JPanel {
productos p=new productos();
    DaoProductos daoP=new DaoProductos();
    DefaultTableModel modelo=new DefaultTableModel();

    Categoria ct=new Categoria();
    DaoCategoria daoCt=new DaoCategoria();
    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
      listarProductos();
        numProducto();
    }

    private void listarProductos(){
        List<productos> lista=daoP.Listar();
        modelo=(DefaultTableModel) tablaProductos.getModel();
        Object[] ob=new Object[5];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdproducto();
            ob[1]=lista.get(i).getNomProd();
            ob[2]=lista.get(i).getStock();
            ob[3]=lista.get(i).getIdCategoria();
            ob[4]=lista.get(i).getPrecioV();
            modelo.addRow(ob);
        }
       tablaProductos.setModel(modelo);
    }

    void numProducto(){
        int numero=daoP.numProducto();
        if(numero==0){
        txtid.setText("1");
        }else{
        int i=numero;
        i=i+1;
        txtid.setText(i+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jpanelRound2 = new Modelo.JpanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidCategoria = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtNomCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btnBuscarIdCategiria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttprecio = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnGuradar = new javax.swing.JButton();
        btnElimar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReporte = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound3 = new Modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1970, 720));
        setPreferredSize(new java.awt.Dimension(1970, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setPreferredSize(new java.awt.Dimension(982, 740));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound2.setBackground(new java.awt.Color(102, 204, 255));
        jpanelRound2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 12))); // NOI18N
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jpanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id categoría ");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 201, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio. V");
        jpanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 328, -1, -1));

        txtidCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtidCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 229, 120, -1));

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, -1));

        txtNomCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtNomCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 288, 270, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 158, 270, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 102, 270, -1));

        btnBuscarIdCategiria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarIdCategiria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/t (1).png"))); // NOI18N
        btnBuscarIdCategiria.setText("Buscar");
        btnBuscarIdCategiria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdCategiriaActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscarIdCategiria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock");
        jpanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 136, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoría ");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 266, -1, -1));

        txttprecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txttprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 350, 270, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_upgrade_recyclearrows_arrow_azul_12426 (1).png"))); // NOI18N
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 440, 150, -1));

        btnGuradar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuradar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/1486564412-plus_81511 (1).png"))); // NOI18N
        btnGuradar.setText("Registrar");
        btnGuradar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuradarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnGuradar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 400, 150, -1));

        btnElimar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnElimar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnElimar.setText("Eliminar");
        btnElimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnElimar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/t (1).png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoAplicacion/logopequeño.png"))); // NOI18N
        jpanelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 200, 160));

        btnReporte.setBackground(new java.awt.Color(213, 137, 137));
        btnReporte.setBackgroundHover(new java.awt.Color(14, 76, 117));
        btnReporte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_DRIVE_FILE);
        btnReporte.setRound(25);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 50, -1));

        jpanelRound1.add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 6, 310, 780));

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 12))); // NOI18N
        jpanelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stocok", "IdCat", "Precio V"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jpanelRound3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 670, 760));

        jpanelRound1.add(jpanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 690, 790));

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
   int fila=tablaProductos.getSelectedRow();
        txtid.setText(tablaProductos.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaProductos.getValueAt(fila, 1).toString());
        txtstock.setText(tablaProductos.getValueAt(fila, 2).toString());
        txtidCategoria.setText(tablaProductos.getValueAt(fila, 3).toString());
        txttprecio.setText(tablaProductos.getValueAt(fila, 4).toString());

        ct.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
        if(daoCt.buscar(ct)){
            txtNomCategoria.setText(ct.getNomCategoria());
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnGuradarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuradarActionPerformed
        p.setIdproducto(Integer.parseInt(txtid.getText()));
        p.setNomProd(txtnombre.getText());
       p.setStock(Integer.parseInt(txtstock.getText()));
        p.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
        p.setPrecioV(Double.parseDouble(txttprecio.getText()));
        if(daoP.insertar(p)){
           
            JOptionPane.showMessageDialog(null,"Producto Registrado Con Exito");
            limpiarTablaProductos();
            listarProductos();
            numProducto();
        }else{
        JOptionPane.showMessageDialog(null, "No se pudo registrar el Producto");   
        }
    }//GEN-LAST:event_btnGuradarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         int fila=tablaProductos.getSelectedRow();
        if(fila==-1&&txtid.getText().isEmpty()){
           
          JOptionPane.showMessageDialog(null,"Seleccione un Proveedor");
        }else{
            p.setIdproducto(Integer.parseInt(txtid.getText()));
            p.setNomProd(txtnombre.getText());
             p.setStock(Integer.parseInt(txtstock.getText()));
            p.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
            p.setPrecioV(Double.parseDouble(txttprecio.getText()));
            if(daoP.editar(p)){
             
                limpiarCampos();
                limpiarTablaProductos();
                listarProductos();
            }else{
              JOptionPane.showMessageDialog(null,"Se edito con exito");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnElimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimarActionPerformed
        if(!txtid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar el Producto?","Confirmar",2);
            if(confirmacion==0){
                p.setIdproducto(Integer.parseInt(txtid.getText()));
                daoP.eliminar(p);
                limpiarCampos();
                limpiarTablaProductos();
                listarProductos();
            
            }
        }else{
          JOptionPane.showMessageDialog(null,"Se elimino con exito");
        }        
    }//GEN-LAST:event_btnElimarActionPerformed

    private void btnBuscarIdCategiriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdCategiriaActionPerformed
        BuscarDato.tipo=true;
        BuscarDato.entrada=false;
        BuscarDato m=new BuscarDato();
        m.setVisible(true);
    }//GEN-LAST:event_btnBuscarIdCategiriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        p.setIdproducto(Integer.parseInt(txtid.getText()));
        if(daoP.buscar(p)){
            txtid.setText(p.getIdproducto()+"");
            txtnombre.setText(p.getNomProd());
            txtidCategoria.setText(p.getIdCategoria()+"");
            txttprecio.setText(p.getPrecioV()+"");
            txtstock.setText(p.getStock()+"");
            ct.setIdCategoria(Integer.parseInt(txtidCategoria.getText()));
            if(daoCt.buscar(ct)){
                txtNomCategoria.setText(ct.getNomCategoria());
            }
        }else{
           JOptionPane.showMessageDialog(null,"El Producto No Existe");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        GenerarPDF("reporteProductos");

    }//GEN-LAST:event_btnReporteActionPerformed
private final Connection conection=new conexion().conectar();
void GenerarPDF(String reporte){
        Map p=new HashMap();
        JasperReport report;
        JasperPrint print;

        try{
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/reportes/"+reporte+".jrxml");
            print=JasperFillManager.fillReport(report,p, conection);
            JasperViewer view=new JasperViewer(print,false);
            view.setTitle("Lista De Entradas");
            view.setVisible(true);
        }catch(JRException e){
            e.printStackTrace();
        }
    }
private void limpiarTablaProductos() {
       for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }

    private void limpiarCampos() {
       txtid.setText("");
txtnombre.setText("");
txtstock.setText("");
txtNomCategoria.setText("");
txttprecio.setText("");
txtidCategoria.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarIdCategiria;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnElimar;
    private javax.swing.JButton btnGuradar;
    private RSMaterialComponent.RSButtonMaterialIconDos btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound3;
    private javax.swing.JTable tablaProductos;
    public static javax.swing.JTextField txtNomCategoria;
    private javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtidCategoria;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttprecio;
    // End of variables declaration//GEN-END:variables
}
