/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoProveedor;
import Modelo.proveedor;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class Provedores extends javax.swing.JPanel {

proveedor p=new proveedor();


    DaoProveedor dao=new DaoProveedor();
    DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form Provedores
     */
    public Provedores() {
    
        initComponents();
     listarProveedor();
    }

   private void listarProveedor(){
        List<proveedor> lista=dao.Listar();
        modelo=(DefaultTableModel) tablaproveedores.getModel();
        Object[] ob=new Object[8];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdProveedor();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getApellido();
            ob[3]=lista.get(i).getDocumento();
            ob[4]=lista.get(i).getActivadad_comercial();
            ob[5]=lista.get(i).getDireccion();
            ob[6]=lista.get(i).getTelefono();
            ob[7]=lista.get(i).getCorreo();
            modelo.addRow(ob);
        }
       tablaproveedores.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaproveedores = new javax.swing.JTable();
        jpanelRound2 = new Modelo.JpanelRound();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtcorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRsocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnReporte = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(1007, 775));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound1.setBackground(new java.awt.Color(204, 204, 204));
        jpanelRound1.setRoundBottomLeft(30);
        jpanelRound1.setRoundBottomRight(30);
        jpanelRound1.setRoundTopLeft(30);
        jpanelRound1.setRoundTopRight(30);

        tablaproveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaproveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Docuento", "Activadad comercial", "Direccion", "Telefono", "Correo"
            }
        ));
        tablaproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaproveedores);

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 900, 290));

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound2.setRoundBottomLeft(30);
        jpanelRound2.setRoundBottomRight(30);
        jpanelRound2.setRoundTopLeft(30);
        jpanelRound2.setRoundTopRight(30);
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 130, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_upgrade_recyclearrows_arrow_azul_12426 (1).png"))); // NOI18N
        btnEditar.setText("Actualizar ");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 150, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/1486564412-plus_81511 (1).png"))); // NOI18N
        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        jpanelRound2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Correo");
        jpanelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        txttelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 190, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Telefono");
        jpanelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Direccion");
        jpanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        txtRsocial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsocialKeyReleased(evt);
            }
        });
        jpanelRound2.add(txtRsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Activadad comercial");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        txtdocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdocumentoFocusLost(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jpanelRound2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 190, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cedula");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        txtapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Apellido");
        jpanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jpanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnBuscar.setText("Buscar Cedula");
        btnBuscar.setFocusable(false);
        btnBuscar.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 160, 40));

        btnReporte.setBackground(new java.awt.Color(213, 137, 137));
        btnReporte.setBackgroundHover(new java.awt.Color(14, 76, 117));
        btnReporte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_DRIVE_FILE);
        btnReporte.setRound(25);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 50, -1));

        add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 760, 320));

        rSLabelBorderRound1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelBorderRound1.setText("Gestion de Proveedores");
        rSLabelBorderRound1.setAlignmentX(0.5F);
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(204, 204, 204));
        rSLabelBorderRound1.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        rSLabelBorderRound1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 440, 61));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRsocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsocialKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRsocialKeyReleased

    private void tablaproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproveedoresMouseClicked
        // TODO add your handling code here:
        int fila=tablaproveedores.getSelectedRow();
        txtid.setText(tablaproveedores.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaproveedores.getValueAt(fila, 1).toString());
        txtapellido.setText(tablaproveedores.getValueAt(fila, 2).toString());
        txtdocumento.setText(tablaproveedores.getValueAt(fila, 3).toString());
        txtRsocial.setText(tablaproveedores.getValueAt(fila, 4).toString());
        txtdireccion.setText(tablaproveedores.getValueAt(fila, 5).toString());
        txttelefono.setText(tablaproveedores.getValueAt(fila, 6).toString());
        txtcorreo.setText(tablaproveedores.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tablaproveedoresMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      int fila=tablaproveedores.getSelectedRow();
        if(fila==-1&&txtid.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Seleccione un Proveedor");
        }else{
            p.setIdProveedor(Integer.parseInt(txtid.getText()));
            p.setNombre(txtnombre.getText());
            p.setApellido(txtapellido.getText());
            p.setDocumento(txtdocumento.getText());
            p.setActivadad_comercial(txtRsocial.getText());
            p.setDireccion(txtdireccion.getText());
            p.setTelefono(txttelefono.getText());
            p.setCorreo(txtcorreo.getText());
            if(dao.editar(p)){
                
             JOptionPane.showMessageDialog(null,"Se modifico con exito");
                limpiarCampos();
                limpiarTablaProveedor();
                listarProveedor();
            }else{
              
                JOptionPane.showMessageDialog(null,"Erorr al modificar el Proveedor");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       int fila=tablaproveedores.getSelectedRow();
        if(fila==-1&&txtid.getText().isEmpty()){
       
        JOptionPane.showMessageDialog(null,"Seleccione un Proveedor");
        }else{
            p.setIdProveedor(Integer.parseInt(txtid.getText()));
            p.setNombre(txtnombre.getText());
            p.setApellido(txtapellido.getText());
            p.setDocumento(txtdocumento.getText());
            p.setActivadad_comercial(txtRsocial.getText());
            p.setDireccion(txtdireccion.getText());
            p.setTelefono(txttelefono.getText());
            p.setCorreo(txtcorreo.getText());
            if(dao.editar(p)){
               
             JOptionPane.showMessageDialog(null,"Se modifico con exito");
                limpiarCampos();
                limpiarTablaProveedor();
                listarProveedor();
            }else{
             
            JOptionPane.showMessageDialog(null,"Erorr al modificar el Proveedor");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   if(!txtid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar el Proveedor?","Confirmar",2);
            if(confirmacion==0){
                p.setIdProveedor(Integer.parseInt(txtid.getText()));
                dao.eliminar(p);
              limpiarCampos();
               limpiarTablaProveedor();
                listarProveedor();
       
              JOptionPane.showMessageDialog(null,"Se Elimino con exito el Proveedor");
            }
        }else{

        JOptionPane.showMessageDialog(null,"Seleccione un Proveedor");
        }        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          p.setDocumento(txtdocumento.getText().trim());

if (p.getDocumento().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, ingrese un documento válido.");
    return;
}

if (dao.buscarDocumento(p)) {
    
    txtid.setText(String.valueOf(p.getIdProveedor()));
    txtnombre.setText(p.getNombre());
    txtapellido.setText(p.getApellido());
    txtdocumento.setText(p.getDocumento());
    txtRsocial.setText(p.getActivadad_comercial());
    txtdireccion.setText(p.getDireccion());
    txttelefono.setText(p.getTelefono());
    txtcorreo.setText(p.getCorreo());
} else {
    
    JOptionPane.showMessageDialog(null, "El proveedor no existe.");
    limpiarCampos();
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
         String correo = txtcorreo.getText().trim();
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
             JOptionPane.showMessageDialog(null, "⚠ Correo no válido. Ejemplo: ejemplo@dominio.com");
            txtcorreo.requestFocus(); 
        }
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtdocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdocumentoFocusLost
         String documento = txtdocumento.getText().trim();
        if (!documento.matches("\\d+")) {
             JOptionPane.showMessageDialog(null, "⚠ El documento debe contener solo números.");
            txtdocumento.requestFocus(); 
        }
    }//GEN-LAST:event_txtdocumentoFocusLost

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); 
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_btnReporteActionPerformed

void limpiarCampos(){
        txtid.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        txtRsocial.setText("");
    }
    
    void limpiarTablaProveedor(){
        for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private RSMaterialComponent.RSButtonMaterialIconDos btnReporte;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private javax.swing.JTable tablaproveedores;
    private javax.swing.JTextField txtRsocial;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
