/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Dao.DaoProveedor;
import Modelo.proveedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class Provedores extends javax.swing.JPanel {
proveedor p=new proveedor();
    DaoProveedor dao=new DaoProveedor();
    DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form Provedores
     */
    public Provedores() {
        initComponents();
     listarProveedor();
    }

   private void listarProveedor(){
        List<proveedor> lista=dao.Listar();
        modelo=(DefaultTableModel) tablaproveedores.getModel();
        Object[] ob=new Object[8];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdProveedor();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getApellido();
            ob[3]=lista.get(i).getDocumento();
            ob[4]=lista.get(i).getRsocial();
            ob[5]=lista.get(i).getDireccion();
            ob[6]=lista.get(i).getTelefono();
            ob[7]=lista.get(i).getCorreo();
            modelo.addRow(ob);
        }
       tablaproveedores.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Modelo.JpanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaproveedores = new javax.swing.JTable();
        jpanelRound2 = new Modelo.JpanelRound();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtcorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRsocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();

        setPreferredSize(new java.awt.Dimension(1007, 775));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaproveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Docuento", "R.Social", "Direccion", "Telefono", "Correo"
            }
        ));
        tablaproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaproveedores);

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 930, 280));

        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 130, -1));

        btnEditar.setText("Actualizar ");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, -1));

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 110, -1));
        jpanelRound2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 190, -1));

        jLabel11.setText("Correo");
        jpanelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));
        jpanelRound2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 190, -1));

        jLabel10.setText("Telefono");
        jpanelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));
        jpanelRound2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, -1));

        jLabel8.setText("Direccion");
        jpanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        txtRsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsocialKeyReleased(evt);
            }
        });
        jpanelRound2.add(txtRsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, -1));

        jLabel7.setText("Razon Social");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        jpanelRound2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 190, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel6.setText("Cedula");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));
        jpanelRound2.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, -1));

        jLabel5.setText("Apellido");
        jpanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jpanelRound2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel3.setText("Nombre");
        jpanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jpanelRound2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, -1));

        jLabel2.setText("ID");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 760, 330));

        rSLabelBorderRound1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelBorderRound1.setText("Gestion de Proveedores");
        rSLabelBorderRound1.setBgBorde(new java.awt.Color(153, 255, 204));
        rSLabelBorderRound1.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 547, 61));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRsocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsocialKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRsocialKeyReleased

    private void tablaproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproveedoresMouseClicked
        // TODO add your handling code here:
        int fila=tablaproveedores.getSelectedRow();
        txtid.setText(tablaproveedores.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaproveedores.getValueAt(fila, 1).toString());
        txtapellido.setText(tablaproveedores.getValueAt(fila, 2).toString());
        txtdocumento.setText(tablaproveedores.getValueAt(fila, 3).toString());
        txtRsocial.setText(tablaproveedores.getValueAt(fila, 4).toString());
        txtdireccion.setText(tablaproveedores.getValueAt(fila, 5).toString());
        txttelefono.setText(tablaproveedores.getValueAt(fila, 6).toString());
        txtcorreo.setText(tablaproveedores.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tablaproveedoresMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         p.setNombre(txtnombre.getText());
        p.setApellido(txtapellido.getText());
        p.setDocumento(txtdocumento.getText());
        p.setRsocial(txtRsocial.getText());
        p.setDireccion(txtdireccion.getText());
        p.setTelefono(txttelefono.getText());
        p.setCorreo(txtcorreo.getText());
        if(dao.insertar(p)){
           // MenuPrincipal m=new MenuPrincipal();
           // m.exito("Proveedor Registrado Con Exito");
            limpiarCampos();
            limpiarTablaProveedor();
            listarProveedor();
        }else{
          //  MenuPrincipal m=new MenuPrincipal();
           // m.error("No se pudo registrar el Proveedor");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       int fila=tablaproveedores.getSelectedRow();
        if(fila==-1&&txtid.getText().isEmpty()){
          //  MenuPrincipal m=new MenuPrincipal();
           // m.advertencia("Seleccione un Proveedor");
        }else{
            p.setIdProveedor(Integer.parseInt(txtid.getText()));
            p.setNombre(txtnombre.getText());
            p.setApellido(txtapellido.getText());
            p.setDocumento(txtdocumento.getText());
            p.setRsocial(txtRsocial.getText());
            p.setDireccion(txtdireccion.getText());
            p.setTelefono(txttelefono.getText());
            p.setCorreo(txtcorreo.getText());
            if(dao.editar(p)){
                //MenuPrincipal m=new MenuPrincipal();
             //   m.exito("Se modifico con exito");
                limpiarCampos();
                limpiarTablaProveedor();
                listarProveedor();
            }else{
              //  MenuPrincipal m=new MenuPrincipal();
               // m.error("Erorr al modificar el Proveedor");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if(!txtid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar el Proveedor?","Confirmar",2);
            if(confirmacion==0){
                p.setIdProveedor(Integer.parseInt(txtid.getText()));
                dao.eliminar(p);
             //   limpiarCampos();
             //   limpiarTablaProveedor();
                listarProveedor();
          //      MenuPrincipal m=new MenuPrincipal();
              //  m.exito("Se Elimino con exito el Proveedor");
            }
        }else{
         //   MenuPrincipal m=new MenuPrincipal();
        //    m.advertencia("Seleccione un Proveedor");
        }        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          p.setDocumento(txtdocumento.getText());
        if(dao.buscarDocumento(p)){
            txtid.setText(p.getIdProveedor()+"");
            txtnombre.setText(p.getNombre());
            txtapellido.setText(p.getApellido());
            txtdocumento.setText(p.getDocumento());
            txtRsocial.setText(p.getRsocial());
            txtdireccion.setText(p.getDireccion());
            txttelefono.setText(p.getTelefono());
            txtcorreo.setText(p.getCorreo());
        }else{
          //  MenuPrincipal m=new MenuPrincipal();
            //m.advertencia("El Proveedor No Existe");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

void limpiarCampos(){
        txtid.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        txtRsocial.setText("");
    }
    
    void limpiarTablaProveedor(){
        for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private javax.swing.JTable tablaproveedores;
    private javax.swing.JTextField txtRsocial;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
