/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ecumarket.ui.forms;

import com.ecumarket.dao.DaoUsuario;
import com.ecumarket.model.usuarios;
import java.awt.Toolkit;

import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO IDEAPAD
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    usuarios u = new usuarios();
    DaoUsuario dao = new DaoUsuario();
    DefaultTableModel modelo = new DefaultTableModel();
    PantallaPrincipal pP;

    public Registro(PantallaPrincipal pPi) {

        initComponents();
        this.pP = pPi;
        listarUsuarios();
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    actualizartablausuarios();
                });
            }
        }, 0, 15000);
    }

    private void actualizartablausuarios() {
        modelo.setRowCount(0);
        listarUsuarios();
    }

    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound2 = new com.ecumarket.util.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbciudad = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtidusuarios = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        txtusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        btnRegistrarse1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1270, 790));
        setPreferredSize(new java.awt.Dimension(1270, 790));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound2.setForeground(new java.awt.Color(0, 153, 255));
        jpanelRound2.setPreferredSize(new java.awt.Dimension(982, 740));
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Ingresa tus datos personales");
        jpanelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("IdUsuario");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("tipoUsuario");
        jpanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Correo");
        jpanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Contraseña");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Telefono");
        jpanelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpanelRound2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 63, 346, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Ciudad");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        cmbciudad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbciudad.setForeground(new java.awt.Color(0, 153, 255));
        cmbciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo de los tsáchilas", "Sucumbíos", "Tungurahua", "Zamora Chinchipe" }));
        jpanelRound2.add(cmbciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 280, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_upgrade_recyclearrows_arrow_azul_12426 (1).png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Cedula");
        jpanelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Dirrección");
        jpanelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Usuario");
        jpanelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Nombre ");
        jpanelRound2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Apellido");
        jpanelRound2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtidusuarios.setEditable(false);
        txtidusuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtidusuarios.setForeground(new java.awt.Color(0, 153, 255));
        txtidusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidusuariosActionPerformed(evt);
            }
        });
        jpanelRound2.add(txtidusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 153, 255));
        jpanelRound2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 280, -1));

        txtapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(0, 153, 255));
        jpanelRound2.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 280, -1));

        txtdocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdocumento.setForeground(new java.awt.Color(0, 153, 255));
        txtdocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdocumentoFocusLost(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jpanelRound2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 280, -1));

        txtdireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 153, 255));
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jpanelRound2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 280, -1));

        txttelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 153, 255));
        jpanelRound2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 280, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 153, 255));
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        jpanelRound2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 280, -1));

        cmbTipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbTipoUsuario.setForeground(new java.awt.Color(0, 153, 255));
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor", "Almacenero" }));
        jpanelRound2.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 280, -1));

        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(0, 153, 255));
        jpanelRound2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 280, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ECUMARKET");
        jpanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 6, -1, -1));
        jpanelRound2.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 6, 57, 48));

        btnRegistrarse1.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarse1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarse1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Usuario/nuevo-cliente.png"))); // NOI18N
        btnRegistrarse1.setText("Registrarse");
        btnRegistrarse1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnRegistrarse1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarse1ActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 160, 40));

        btnEliminar.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 130, 40));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/t (1).png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 120, 40));

        txtpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 280, -1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Docuento", "Direccion", "Telefono", "Correo", "TipoUser", "Usuario", "Pass"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jpanelRound2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 510, 614));

        btnvolver.setBackground(new java.awt.Color(0, 153, 255));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/return_121764 (1).png"))); // NOI18N
        btnvolver.setText("Login");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 120, 40));

        add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));
    }// </editor-fold>//GEN-END:initComponents
private void listarUsuarios() {
        List<usuarios> lista = dao.Listar();
        modelo = (DefaultTableModel) tablaUsuarios.getModel();
        Object[] ob = new Object[10];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getIdusuario();
            ob[1] = lista.get(i).getNombre();
            ob[2] = lista.get(i).getApellido();
            ob[3] = lista.get(i).getDocumento();
            ob[4] = lista.get(i).getDireccion();
            ob[5] = lista.get(i).getTelefono();
            ob[6] = lista.get(i).getCorreo();
            ob[7] = lista.get(i).getTipoUsuario();
            ob[8] = lista.get(i).getUsuario();
            ob[9] = lista.get(i).getPassword();

            modelo.addRow(ob);
        }
        tablaUsuarios.setModel(modelo);
    }

    void limpiarCampos() {
        txtidusuarios.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        txtusuario.setText("");
        txtpass.setText("");
    }

    void limpiarTablaUsuarios() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = 0 - 1;
        }
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        if (fila == -1 && txtidusuarios.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un usuario para modificar.");
        } else {
            u.setIdusuario(Integer.parseInt(txtidusuarios.getText()));
            u.setNombre(txtnombre.getText());
            u.setApellido(txtapellido.getText());
            u.setDocumento(txtdocumento.getText());
            u.setDireccion(txtdireccion.getText());
            u.setTelefono(txttelefono.getText());
            u.setCorreo(txtcorreo.getText());
            u.setTipoUsuario(cmbTipoUsuario.getSelectedItem().toString());
            u.setUsuario(txtusuario.getText());
            u.setPassword(txtpass.getText());

            if (dao.existeUsuarioParaOtro(u.getUsuario(), u.getIdusuario())) {
                JOptionPane.showMessageDialog(null, "🚫 El nombre de usuario ya está en uso por otro usuario.");
                return;
            }

            if (dao.editar(u.getNombre(), u.getApellido(), u.getDocumento(), u.getDireccion(), u.getTelefono(), u.getCorreo(), u.getTipoUsuario(), u.getUsuario(), u.getPassword(), u.getIdusuario())) {
                JOptionPane.showMessageDialog(null, "✅ Se modificó con éxito el usuario.");
                limpiarCampos();
                limpiarTablaUsuarios();
                listarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "❌ Error al modificar el usuario.");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtidusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidusuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidusuariosActionPerformed

    private void btnRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse1ActionPerformed
        u.setNombre(txtnombre.getText());
        u.setApellido(txtapellido.getText());
        u.setDocumento(txtdocumento.getText());
        u.setDireccion(txtdireccion.getText());
        u.setTelefono(txttelefono.getText());
        u.setCorreo(txtcorreo.getText());
        u.setTipoUsuario(cmbTipoUsuario.getSelectedItem().toString());
        u.setUsuario(txtusuario.getText());
        u.setPassword(txtpass.getText());

        try {
            if (dao.existeUsuarioParaOtro(u.getUsuario(), u.getIdusuario())) {
                JOptionPane.showMessageDialog(null, "🚫 El nombre de usuario ya está en uso por otro usuario.");
                return;
            }
            if (dao.insertar(u.getNombre(), u.getApellido(), u.getDocumento(), u.getDireccion(), u.getTelefono(), u.getCorreo(), u.getTipoUsuario(), u.getUsuario(), u.getPassword())) {
                JOptionPane.showMessageDialog(null, "✅ Usuario Registrado con Éxito");
                limpiarCampos();
                limpiarTablaUsuarios();
                listarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se pudo registrar el usuario");
            }
        } catch (Exception e) {
            if (e.getMessage().contains("Duplicate entry") && e.getMessage().contains("usuario")) {
                JOptionPane.showMessageDialog(null, "🚫 El nombre de usuario ya está en uso. Elige otro.");
            } else {
                JOptionPane.showMessageDialog(null, "⚠️ Error al registrar usuario: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarse1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtidusuarios.getText().isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Es tas seguro de eliminar el Usuario?", "Confirmar", 2);
            if (confirmacion == 0) {
                u.setIdusuario(Integer.parseInt(txtidusuarios.getText()));
                dao.eliminar(u);
                limpiarCampos();
                limpiarTablaUsuarios();
                listarUsuarios();

                JOptionPane.showMessageDialog(null, "Se Elimino con exito el Usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Usuario");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        u.setDocumento(txtdocumento.getText());
        if (dao.buscar(u)) {
            txtidusuarios.setText(u.getIdusuario() + "");
            txtnombre.setText(u.getNombre());
            txtapellido.setText(u.getApellido());
            txtdocumento.setText(u.getDocumento());
            txtdireccion.setText(u.getDireccion());
            txttelefono.setText(u.getTelefono());
            txtcorreo.setText(u.getCorreo());
            txtusuario.setText(u.getUsuario());
            txtpass.setText(u.getPassword());
            cmbTipoUsuario.setSelectedItem(u.getTipoUsuario());
        } else {
            JOptionPane.showMessageDialog(null, "El Usuario No Existe");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        int fila = tablaUsuarios.getSelectedRow();
        txtidusuarios.setText(tablaUsuarios.getValueAt(fila, 0).toString());
        txtnombre.setText(tablaUsuarios.getValueAt(fila, 1).toString());
        txtapellido.setText(tablaUsuarios.getValueAt(fila, 2).toString());
        txtdocumento.setText(tablaUsuarios.getValueAt(fila, 3).toString());
        txtdireccion.setText(tablaUsuarios.getValueAt(fila, 4).toString());
        txttelefono.setText(tablaUsuarios.getValueAt(fila, 5).toString());
        txtcorreo.setText(tablaUsuarios.getValueAt(fila, 6).toString());
        cmbTipoUsuario.setSelectedItem(tablaUsuarios.getValueAt(fila, 7).toString());
        txtusuario.setText(tablaUsuarios.getValueAt(fila, 8).toString());

        u.setDocumento(txtdocumento.getText());
        if (dao.buscar(u)) {
            txtpass.setText(u.getPassword());
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Esta acción también hará cerrar la sesión actual, desea continuar?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            pP.dispose();
            new Login().setVisible(true);
        }

    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtdocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdocumentoFocusLost
        String documento = txtdocumento.getText().trim();
        if (!documento.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, " El documento debe contener solo números.");
            txtdocumento.requestFocus();
        }
    }//GEN-LAST:event_txtdocumentoFocusLost

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
        String correo = txtcorreo.getText().trim();
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(null, " Correo no válido. Ejemplo: ejemplo@dominio.com");
            txtcorreo.requestFocus();
        }
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped

    }//GEN-LAST:event_txtdireccionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarse1;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JComboBox<String> cmbciudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ecumarket.util.JpanelRound jpanelRound2;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtidusuarios;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
