/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;


import Dao.DaoClientes;
import Dao.DaoDetalleSalida;
import Dao.DaoEntradas;
import Dao.DaoProductos;
import Dao.DaoSalida;
import Dao.conexion;
import Modelo.clientes;
import Modelo.entradas;
import Modelo.salidas;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;




/**
 *
 * @author Personal
 */
public class Salidas extends javax.swing.JPanel {
salidas s=new salidas();
DaoSalida daoS=new DaoSalida();
DaoDetalleSalida daoDS=new DaoDetalleSalida();
clientes c=new clientes();
DaoClientes daoC=new DaoClientes();
DefaultTableModel modelo=new DefaultTableModel();

entradas e=new entradas();
DaoEntradas DaoE=new DaoEntradas();
DaoProductos daoPR=new DaoProductos();
int filaSeleccionada;
    /**
     * Creates new form Salidas
     */
    public Salidas() {
        initComponents();
    numSalida();
    }

    void numSalida(){
        String numero=daoS.numSalida();
        if(numero==null){
        txtnsalida.setText("001");
        }else{
        int i=Integer.parseInt(numero);
        i=i+1;
        txtnsalida.setText("00"+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSTextFullRound1 = new rojeru_san.rsfield.RSTextFullRound();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jpanelRound1 = new Modelo.JpanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        txtprecio = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtnsalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarClientes = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtidProducto = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        jpanelRound5 = new Modelo.JpanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtigv = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jpanelRound4 = new Modelo.JpanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        jpanelRound2 = new Modelo.JpanelRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        txtnombreCliente = new javax.swing.JTextField();

        rSTextFullRound1.setText("rSTextFullRound1");

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Total:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 1201, -1, -1));

        jLabel18.setText("IGV:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 1167, -1, -1));

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Datos de Entrada de Producto ");
        jpanelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("ID");
        jpanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Nombre");
        jpanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Fecha Salida");
        jpanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jcFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpanelRound1.add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 202, -1));

        txtprecio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        txtcantidad.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound1.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 173, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Cantidad");
        jpanelRound1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Precio");
        jpanelRound1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Stock Disponible");
        jpanelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound1.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        txtnsalida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnsalida.setForeground(new java.awt.Color(153, 153, 153));
        jpanelRound1.add(txtnsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Numero de Pedidos");
        jpanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        btnBuscarClientes.setText("Buscar Producto");
        btnBuscarClientes.setFocusPainted(false);
        btnBuscarClientes.setFocusable(false);
        btnBuscarClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });
        jpanelRound1.add(btnBuscarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 171, -1));

        txtidProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound1.add(txtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        txtproducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound1.add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        add(jpanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 530, 340));

        jpanelRound5.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Sub Total:");
        jpanelRound5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Iva 12%");
        jpanelRound5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setText("Total:");
        jpanelRound5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound5.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 142, -1));

        txtigv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound5.add(txtigv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 142, -1));

        txtsubtotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtsubtotal.setToolTipText("");
        txtsubtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanelRound5.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 142, -1));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/1486564412-plus_81511 (1).png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpanelRound5.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btnRecargar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/file-edit_114433 (1).png"))); // NOI18N
        btnRecargar.setText("Editar ");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        jpanelRound5.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_exit_delete_delete_12417 (1).png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jpanelRound5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/blue_upgrade_recyclearrows_arrow_azul_12426 (1).png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jpanelRound5.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/logopequeño.png"))); // NOI18N
        jpanelRound5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 80));

        add(jpanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 270, 350));

        jpanelRound4.setBackground(new java.awt.Color(204, 204, 204));

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDSAlida", "ID Entrada", "Producto", "Precio U.", "Cant.", "Importe"
            }
        ));
        tablaSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaSalidas);

        javax.swing.GroupLayout jpanelRound4Layout = new javax.swing.GroupLayout(jpanelRound4);
        jpanelRound4.setLayout(jpanelRound4Layout);
        jpanelRound4Layout.setHorizontalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jpanelRound4Layout.setVerticalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        add(jpanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 650, 350));

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Datos del Cliente");
        jpanelRound2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("ID");
        jpanelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Nombre Del Producto");
        jpanelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        btnBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes Loginregister/t (1).png"))); // NOI18N
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 123, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Teléfono");
        jpanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Correo");
        jpanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Cedula del cliente");
        jpanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtdocumento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jpanelRound2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        txtidcliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound2.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        txtnombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jpanelRound2.add(txtnombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 380, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
       c.setDocumento(txtdocumento.getText());
        if(daoC.buscar(c)){
            txtidcliente.setText(c.getIdCliente()+"");
            txtnombreCliente.setText(c.getNombre()+" "+c.getApellido());
            txtdocumento.setText(c.getDocumento());
            txtTelefono.setText(c.getTelefono());
            txtcorreo.setText(c.getCorreo());
        }else{
           
     JOptionPane.showMessageDialog(null,"No se encuentra el producto");
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed


        for(int i=0;i<tablaSalidas.getRowCount();i++){
            if(tablaSalidas.getValueAt(i, 1).toString().equals(txtidProducto.getText())){
      
            JOptionPane.showMessageDialog(null,"El Producto ya esta agregado");
                modelo.removeRow(i);
            }
        }
        agregaEntrada();
        limpiarDatosPod();
        sumarTotal();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        
   double precio,cant;
        precio=Double.parseDouble(txtprecio.getText());
        cant=Double.parseDouble(txtcantidad.getText());
        modelo.setValueAt(txtcantidad.getText().trim(), filaSeleccionada, 4);
        modelo.setValueAt((precio*cant)+"", filaSeleccionada, 5);
        sumarTotal();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(filaSeleccionada==-1){
          
         JOptionPane.showMessageDialog(null,"Seleccione un producto de la tabla para eliminar");
        }else{
            modelo.removeRow(filaSeleccionada);
            sumarTotal();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
    s.setNumSalida(txtnsalida.getText());
        s.setIdCliente(Integer.parseInt(txtidcliente.getText()));
        s.setSubtotal(Double.parseDouble(txtsubtotal.getText()));
        s.setIgv(Double.parseDouble(txtigv.getText()));
        s.setTotal(Double.parseDouble(txtTotal.getText()));
        Calendar cal;
        int d,m,a;
        cal=jcFecha.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        s.setFecha(new Date(a,m,d));
        if(daoS.insertar(s)){
            guardarDetalle();
           
           JOptionPane.showMessageDialog(null,"Salida Registrada Con Exito");
            restaStock();
           GenerarPDF(txtnsalida.getText());
            numSalida();
            limpiarDatosPod();
            limpaDatosCliente();
            txtTotal.setText("");
            txtsubtotal.setText("");
            txtigv.setText("");
            limpiarTablaSalida();
        }else{
            
           JOptionPane.showMessageDialog(null,"No se pudo registrar la Salida");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void tablaSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidasMouseClicked
  filaSeleccionada=tablaSalidas.getSelectedRow();
        txtidProducto.setText(tablaSalidas.getValueAt(filaSeleccionada, 1).toString());
        txtcantidad.setText(tablaSalidas.getValueAt(filaSeleccionada, 4).toString());
        txtproducto.setText(tablaSalidas.getValueAt(filaSeleccionada, 2).toString());
        txtprecio.setText(tablaSalidas.getValueAt(filaSeleccionada, 3).toString());

        e.setIdentrada(Integer.parseInt(txtidProducto.getText()));
        if(DaoE.buscar(e)){
           txtstock.setText(e.getStock()+"");
        }
    }//GEN-LAST:event_tablaSalidasMouseClicked

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
    BuscaProductos.tipo=true;
        BuscaProductos m=new BuscaProductos();
        m.setVisible(true);
    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtdocumentoKeyTyped
private void agregaEntrada(){
        double precio,total,importe;
        modelo=(DefaultTableModel) tablaSalidas.getModel();
        int idEntrada=Integer.parseInt(txtidProducto.getText());
        int idSalida=Integer.parseInt(txtnsalida.getText());
        int cantidad=Integer.parseInt(txtcantidad.getText());
        precio=Double.parseDouble(txtprecio.getText());
        String prod=txtproducto.getText();
        importe=cantidad*precio;
        int stock=Integer.parseInt(txtstock.getText());
        ArrayList lista=new ArrayList();
        if(stock>0 && cantidad<=stock){
            lista.add(idSalida);
            lista.add(idEntrada);
            lista.add(prod);
            lista.add(precio);
            lista.add(cantidad);
            lista.add(importe);
            Object[] ob=new Object[6];
            ob[0]=lista.get(0);
            ob[1]=lista.get(1);
            ob[2]=lista.get(2);
            ob[3]=lista.get(3);
            ob[4]=lista.get(4);
            ob[5]=lista.get(5);
            modelo.addRow(ob);
            tablaSalidas.setModel(modelo);
        }else{
          JOptionPane.showMessageDialog(null, "No se pudo registrar.");
        }
    }

    void guardarDetalle(){
        for(int i=0;i<tablaSalidas.getRowCount();i++){
        int idSalida=Integer.parseInt(tablaSalidas.getValueAt(i, 0).toString());
        int idEntrada=Integer.parseInt(tablaSalidas.getValueAt(i, 1).toString());
        int cant=Integer.parseInt(tablaSalidas.getValueAt(i, 4).toString());
        Double importe=Double.valueOf(tablaSalidas.getValueAt(i, 5).toString());
        daoDS.insertar(idSalida, idEntrada, cant, importe);
        }
    }

    void restaStock(){
        for(int i=0;i<tablaSalidas.getRowCount();i++){
        int idEntrada=Integer.parseInt(tablaSalidas.getValueAt(i, 1).toString());
        int cant=Integer.parseInt(tablaSalidas.getValueAt(i, 4).toString());
        daoPR.restarStock(idEntrada, cant);
        }
    }

    void sumarTotal(){
        double fila,igv,subtotal,total = 0.00;
        for(int i=0;i<tablaSalidas.getRowCount();i++){
        fila=Double.parseDouble(tablaSalidas.getValueAt(i, 5).toString());
        total+=fila;
        igv=total*0.18;
        subtotal=total-igv;
        txtTotal.setText(String.format("%.2f", total).replace(",", "."));
        txtsubtotal.setText(String.format("%.2f", subtotal).replace(",", "."));
        txtigv.setText(String.format("%.2f", igv).replace(",", "."));
        }
    }

    void limpiarDatosPod(){
        txtidProducto.setText("");
        txtproducto.setText("");
        txtstock.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
    }

    void limpaDatosCliente(){
        txtTelefono.setText("");
        txtdocumento.setText("");
        txtidcliente.setText("");
        txtnombreCliente.setText("");
        txtcorreo.setText("");
    }

    void limpiarTablaSalida(){
        for(int i=0;i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=0-1;
        }
    }
  private final Connection conection=new conexion().conectar();

    void GenerarPDF(String numSalida){
        Map p=new HashMap();
        p.put("numSalida", numSalida);
        JasperReport report;
        JasperPrint print;

        try{
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/reportes/Salida.jrxml");
            print=JasperFillManager.fillReport(report, p, conection);
            JasperViewer view=new JasperViewer(print,false);
            view.setTitle("Documento Salida N° "+numSalida);
            view.setVisible(true);
        }catch(JRException e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarClientes;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jcFecha;
    private Modelo.JpanelRound jpanelRound1;
    private Modelo.JpanelRound jpanelRound2;
    private Modelo.JpanelRound jpanelRound4;
    private Modelo.JpanelRound jpanelRound5;
    private rojeru_san.rsfield.RSTextFullRound rSTextFullRound1;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdocumento;
    public static javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnombreCliente;
    private javax.swing.JLabel txtnsalida;
    public static javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtproducto;
    public static javax.swing.JTextField txtstock;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
